<!-- footer -->

<div class="footer">
    <div class="footer-grids">
        <div class="footer-top">
            <div class="footer-top-nav">
                <ul>
                    <li><a href="javascript:void(0);">Bản quyền thuộc BlueMobile VietNam</a></li>
                    <li><a href="javascript:void(0);">Giấy Phép MXH 266/GP- BTTTT</a></li>
                    <li><a href="javascript:void(0);">Cấp ngày: 09/06/2017 Nơi cấp: Bộ Thông tin truyền thông</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-bottom">
            <ul>
                <?php if($applogin){?>
                    <li><a href="/sub/logout"class="f-history f-help">退出</a></li>
                <?php }else{?>
                    <li><a href="/sub/login" class="f-history">管理员</a></li>
                <?php }?>
            </ul>
        </div>
    </div>

    <!--div class="footer-grids">
        <div class="footer-top">
            <div class="footer-top-nav">
                <ul>
                    <li><a href="about.html">About</a></li>
                    <li><a href="press.html">Press</a></li>
                    <li><a href="copyright.html">Copyright</a></li>
                    <li><a href="creators.html">Creators</a></li>
                    <li><a href="#">Advertise</a></li>
                    <li><a href="developers.html">Developers</a></li>
                </ul>
            </div>
            <div class="footer-bottom-nav">
                <ul>
                    <li><a href="terms.html">Terms</a></li>
                    <li><a href="privacy.html">Privacy</a></li>
                    <li><a href="#small-dialog4" class="play-icon popup-with-zoom-anim">Send feedback</a></li>
                    <li><a href="privacy.html">Policy & Safety </a></li>
                    <li><a href="try.html">Try something new!</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-bottom">
            <ul>
                <li class="languages">
                    <select class="form-control bfh-countries" data-country="US">
                        <option value="">Select Language</option>
                        <option>Spanish</option>
                        <option>French</option>
                        <option>German</option>
                        <option>Malayalam</option>
                        <option>Cajun</option>
                        <option>Amharic</option>
                    </select>
                </li>
                <li class="languages">
                    <select class="form-control bfh-countries">
                        <option value="">Select Country</option>
                        <option value="VCT">Saint Vincent and the Grenadines</option>
                        <option value="WSM">Samoa</option>
                        <option value="SMR">San Marino</option>
                        <option value="STP">Sao Tome and Principe</option>
                        <option value="ZMB">Zambia</option>
                        <option value="ZWE">Zimbabwe</option>
                    </select>
                </li>
                <li class="languages">
                    <select class="form-control bfh-countries" data-country="US">
                        <option value="">Safety Off</option>
                        <option value="">Safety On</option>
                    </select>
                </li>
                <li><a href="history.html" class="f-history">History</a></li>
                <li><a href="#small-dialog5" class="play-icon popup-with-zoom-anim f-history f-help">Help</a></li>
            </ul>
        </div>
    </div-->
</div>
<!-- //footer -->
</div>
<div class="clearfix"> </div>
<div class="drop-menu">
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Regular link</a></li>
        <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#">Disabled link</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another link</a></li>
    </ul>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/assets/js/bootstrap.min.js"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
</body>
</html>