<!-- footer -->

<div class="footer">
    <div class="footer-grids">
        <div class="footer-top">
            <div class="footer-top-nav">
                <ul>
                    <li><a href="javascript:void(0);">Bản quyền thuộc BlueMobile VietNam</a></li>
                    <li><a href="javascript:void(0);">Giấy Phép MXH 266/GP- BTTTT</a></li>
                    <li><a href="javascript:void(0);">Cấp ngày: 09/06/2017 Nơi cấp: Bộ Thông tin truyền thông</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-bottom">
            <ul>
                <?php if($applogin){?>
                    <li><a href="/sub/logout"class="f-history f-help">退出</a></li>
                <?php }else{?>
                    <li><a href="/sub/login" class="f-history">管理员</a></li>
                <?php }?>
            </ul>
        </div>
    </div>
</div>
<!-- //footer -->
</div>
<div class="clearfix"> </div>
<div class="drop-menu">
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Regular link</a></li>
        <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#">Disabled link</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another link</a></li>
    </ul>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/assets/js/bootstrap.min.js"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
</body>
</html>

<script>
    // 获取URL参数
    function GetQueryString(name)
   {
       var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)");
       var r = window.location.search.substr(1).match(reg);
       if (r != null)
           return  unescape(r[2]);
       return null;
   }
   
   // 定义提示
   var statusMsg = new Array();
   statusMsg[200] = 'Subscribe to the success';
   statusMsg[400] = 'Subscribe to the failure';
   statusMsg[201] = 'Unsubscribe success';
   statusMsg[401] = 'Unsubscribe failure';
</script>