
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $site['siteUrl']; ?>"><h1><img src="<?php echo $site['log']; ?>" alt="" /></h1></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <!--搜索框-->
            <!--div class="top-search">
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Search...">
                    <input type="submit" value=" ">
                </form>
            </div-->


            <div class="header-top-right">

                <!--div class="file">
                    <a href="upload.html">Upload</a>
                </div-->


                <div class="signin">
                    <!--探测到手机号，直接直接订阅按钮-->
                    <style>
                    @media screen and (max-width: 480px){
                        .signin a.play-icons{
                            width: 95%;
                            display: inline-block;
                            margin-bottom: 2px;
                            text-align: center;
                        }
                    }
                    </style>
                    <?php if (netType() == '3G') { foreach (videoURL() as $val){ ?>
                        <a class="play-icon play-icons" href="<?php echo $val[0]; ?>" role="button"><?php echo $val[1];?></a>
                    <?php }} ?>
                    <!--右上角 登录直接取消-->
                    <!--a href="#small-dialog2" class="play-icon popup-with-zoom-anim">Sign Up</a-->
                    <!-- pop-up-box -->
                    <script type="text/javascript" src="/assets/js/modernizr.custom.min.js"></script>    
                    <link href="/assets/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
                    <script src="/assets/js/jquery.magnific-popup.js" type="text/javascript"></script>
                    <!--//pop-up-box -->
                    <div id="small-dialog2" class="mfp-hide">
                        <h3>Create Account</h3> 
                        <div class="social-sits">
                            <div class="facebook-button">
                                <a href="#">Connect with Facebook</a>
                            </div>
                            <div class="chrome-button">
                                <a href="#">Connect with Google</a>
                            </div>
                            <div class="button-bottom">
                                <p>Already have an account? <a href="#small-dialog" class="play-icon popup-with-zoom-anim">Login</a></p>
                            </div>
                        </div>
                        <div class="signup">
                            <form>
                                <input type="text" class="email" placeholder="Mobile Number" maxlength="10" pattern="[1-9]{1}\d{9}" title="Enter a valid mobile number" />
                            </form>
                            <div class="continue-button">
                                <a href="#small-dialog3" class="hvr-shutter-out-horizontal play-icon popup-with-zoom-anim">CONTINUE</a>
                            </div>
                        </div>
                        <div class="clearfix"> </div>
                    </div>	
                    <div id="small-dialog3" class="mfp-hide">
                        <h3>Create Account</h3> 
                        <div class="social-sits">
                            <div class="facebook-button">
                                <a href="#">Connect with Facebook</a>
                            </div>
                            <div class="chrome-button">
                                <a href="#">Connect with Google</a>
                            </div>
                            <div class="button-bottom">
                                <p>Already have an account? <a href="#small-dialog" class="play-icon popup-with-zoom-anim">Login</a></p>
                            </div>
                        </div>
                        <div class="signup">
                            <form>
                                <input type="text" class="email" placeholder="Email" required="required" pattern="([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?" title="Enter a valid email"/>
                                <input type="password" placeholder="Password" required="required" pattern=".{6,}" title="Minimum 6 characters required" autocomplete="off" />
                                <input type="text" class="email" placeholder="Mobile Number" maxlength="10" pattern="[1-9]{1}\d{9}" title="Enter a valid mobile number" />
                                <input type="submit"  value="Sign Up"/>
                            </form>
                        </div>
                        <div class="clearfix"> </div>
                    </div>	
                    <div id="small-dialog7" class="mfp-hide">
                        <h3>Create Account</h3> 
                        <div class="social-sits">
                            <div class="facebook-button">
                                <a href="#">Connect with Facebook</a>
                            </div>
                            <div class="chrome-button">
                                <a href="#">Connect with Google</a>
                            </div>
                            <div class="button-bottom">
                                <p>Already have an account? <a href="#small-dialog" class="play-icon popup-with-zoom-anim">Login</a></p>
                            </div>
                        </div>
                        <div class="signup">
                            <form action="upload.html">
                                <input type="text" class="email" placeholder="Email" required="required" pattern="([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?" title="Enter a valid email"/>
                                <input type="password" placeholder="Password" required="required" pattern=".{6,}" title="Minimum 6 characters required" autocomplete="off" />
                                <input type="submit"  value="Sign In"/>
                            </form>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div id="small-dialog8" class="mfp-hide">
                        <h3>Subscribe to our newsletters</h3> 
                        <div class="signup subscribe-grid">
                            <form>
                                <input type="text" class="email" placeholder="Email" required="required" pattern="([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?" title="Enter a valid email"/>
                                <input type="submit"  value="Subscribe"/>
                            </form>
                        </div>
                    </div>
                    <div id="small-dialog4" class="mfp-hide">
                        <h3>Feedback</h3> 
                        <div class="feedback-grids">
                            <div class="feedback-grid">
                                <p>Suspendisse tristique magna ut urna pellentesque, ut egestas velit faucibus. Nullam mattis lectus ullamcorper dui dignissim, sit amet egestas orci ullamcorper.</p>
                            </div>
                            <div class="button-bottom">
                                <p><a href="#small-dialog" class="play-icon popup-with-zoom-anim">Sign in</a> to get started.</p>
                            </div>
                        </div>
                    </div>
                    <div id="small-dialog5" class="mfp-hide">
                        <h3>Help</h3> 
                        <div class="help-grid">
                            <p>Suspendisse tristique magna ut urna pellentesque, ut egestas velit faucibus. Nullam mattis lectus ullamcorper dui dignissim, sit amet egestas orci ullamcorper.</p>
                        </div>
                        <div class="help-grids">
                            <div class="help-button-bottom">
                                <p><a href="#small-dialog4" class="play-icon popup-with-zoom-anim">Feedback</a></p>
                            </div>
                            <div class="help-button-bottom">
                                <p><a href="#small-dialog6" class="play-icon popup-with-zoom-anim">Lorem ipsum dolor sit amet</a></p>
                            </div>
                            <div class="help-button-bottom">
                                <p><a href="#small-dialog6" class="play-icon popup-with-zoom-anim">Nunc vitae rutrum enim</a></p>
                            </div>
                            <div class="help-button-bottom">
                                <p><a href="#small-dialog6" class="play-icon popup-with-zoom-anim">Mauris at volutpat leo</a></p>
                            </div>
                            <div class="help-button-bottom">
                                <p><a href="#small-dialog6" class="play-icon popup-with-zoom-anim">Mauris vehicula rutrum velit</a></p>
                            </div>
                            <div class="help-button-bottom">
                                <p><a href="#small-dialog6" class="play-icon popup-with-zoom-anim">Aliquam eget ante non orci fac</a></p>
                            </div>
                        </div>
                    </div>
                    <div id="small-dialog6" class="mfp-hide">
                        <div class="video-information-text">
                            <h4>Video information & settings</h4>
                            <p>Suspendisse tristique magna ut urna pellentesque, ut egestas velit faucibus. Nullam mattis lectus ullamcorper dui dignissim, sit amet egestas orci ullamcorper.</p>
                            <ol>
                                <li>Nunc vitae rutrum enim. Mauris at volutpat leo. Vivamus dapibus mi ut elit fermentum tincidunt.</li>
                                <li>Nunc vitae rutrum enim. Mauris at volutpat leo. Vivamus dapibus mi ut elit fermentum tincidunt.</li>
                                <li>Nunc vitae rutrum enim. Mauris at volutpat leo. Vivamus dapibus mi ut elit fermentum tincidunt.</li>
                                <li>Nunc vitae rutrum enim. Mauris at volutpat leo. Vivamus dapibus mi ut elit fermentum tincidunt.</li>
                                <li>Nunc vitae rutrum enim. Mauris at volutpat leo. Vivamus dapibus mi ut elit fermentum tincidunt.</li>
                            </ol>
                        </div>
                    </div>
                    <script>
                        $(document).ready(function () {
                            $('.popup-with-zoom-anim').magnificPopup({
                                type: 'inline',
                                fixedContentPos: false,
                                fixedBgPos: true,
                                overflowY: 'auto',
                                closeBtnInside: true,
                                preloader: false,
                                midClick: true,
                                removalDelay: 300,
                                mainClass: 'my-mfp-zoom-in'
                            });

                        });
                    </script>	
                </div>
                <div class="signin">
                    <!--登录 WIFI 直接使用SMS登录-->
                    <?php if (netType() == 'WIFI') { ?>
                        <a href="#small-dialog" class="play-icon popup-with-zoom-anim">Sign In</a>
                    <?php } ?>
                    <div id="small-dialog" class="mfp-hide">
                        <h3>Login</h3>
                        <!--viettel-->
                        <?php 
                            $Telco_array = getTelco();
                            $operator = $Telco_array['operator'];
                            if($operator =='viettel'){ 
                        ?>
                        <div class="social-sits">
                            <p><b>số điện thoại/mật khẩu để đăng nhập. Nếu Quý khách quên mật khẩu, soạn MK gửi 5598.</b></p>
                            <p class="play-icon popup-with-zoom-anim">- Nếu Quý khách chưa đăng ký dịch vụ, hãy soạn:</p>
                            <p class="play-icon popup-with-zoom-anim">+ Gói ngày DK1 gửi 5598 (3.000đ/ngày, gia hạn hàng ngày)</p>
                            <p class="play-icon popup-with-zoom-anim">+ Gói ngày DK7 gửi 5598 (7.000đ/tuần, gia hạn hàng tuần)</p>
                        </div>
                        <?php }else if($operator =='vinaphone'){?>
                        
                        <?php }else if($operator =='mobifone'){?>
                        <!--mobifone-->
                         <div class="social-sits">
                            <p><b> Hệ thống không nhận diện được thuê bao quý khách, nếu quý khách đã đăng ký dịch vụ vui lòng đăng nhập với tài khoản và mật khẩu .</b></p>
                            <p class="play-icon popup-with-zoom-anim">- Nếu quên mật khẩu soạn PW gửi 9210 Nếu quý khách chưa đăng ký sử dụng dịch vụ: </p>
                            <p class="play-icon popup-with-zoom-anim">+ Vui lòng sử dụng 3G/GPRS để đăng ký hoặc soạn tin nhắn theo cú pháp:</p>
                            <p class="play-icon popup-with-zoom-anim">+ DK BD gửi 9210 để tải game ngày (2000d/ngày)</p>
                            <p class="play-icon popup-with-zoom-anim">+ DK BW gửi 9210 để tải game tuần (10000d/tuần)</p>
                            <p class="play-icon popup-with-zoom-anim">+ Hoặc sử dụng GPRS/3G để tải game </p>
                        </div>
                        <?php }?>
                        <style>
                            .telcoGroup{
                                margin-bottom: 10px;
                            }
                            .telcoClass{
                                color: #817F7F;
                                border: solid 1px #817F7F;
                            }
                            .radiusLeftClass{
                                border-top-left-radius: 0;
                                border-bottom-left-radius: 0;
                            }
                            .radiusRightClass{
                                border-top-right-radius: 0;
                                border-bottom-right-radius: 0;
                            }
                            .selectClass{
                                background-color: #21DEEF;
                                color:#F7F7F7;
                            }
                            
                        </style>
                        <div class="signup">
                            <form class="form-horizontal" onsubmit="return false;">                            
                                <div class="btn-group telcoGroup" role="group" >
                                    <button type="button" class="btn btn-default telcoClass radiusLeftClass <?php echo $operator=='viettel'? 'selectClass':''; ?>" value="viettel">viettel</button>
                                    <button type="button" class="btn btn-default telcoClass <?php echo $operator=='vinaphone'? 'selectClass':''; ?>" value="vinaphone">vinaphone</button>
                                    <button type="button" class="btn btn-default telcoClass radiusRightClass <?php echo $operator=='mobifone'? 'selectClass':''; ?>" value="mobifone">mobifone</button>
                                </div>

                                <input type="text" id="msisdn" name="msisdn" class="email" placeholder="Enter mobile" required="required" pattern="^[0-9]{6,16}$"/>
                                <input type="password" id="password" name="password" placeholder="Password" required="required" pattern=".{4,}" title="Minimum 6 characters required" autocomplete="off" />
                                <input type="submit" id="submitButton" value="LOGIN"/>
                            </form>
                            <script src="/dialog/jq_mydialog.js"></script>
                            <link href="/dialog/my_dialog.css" type="text/css" rel="stylesheet" />
                            <script>
                                $(document).ready(function () {
                                    $(document).on('click', '.telcoGroup .telcoClass', function () {
                                        $(this).siblings('.telcoClass').removeClass('selectClass');//  移除同类状态标示
                                        $(this).addClass('selectClass');
                                        $('#submitButton').attr('data', $(this).val());// 设置值
                                    });

                                    // 保存状态
                                    $('#submitButton').click(function () {
                                        //console.log(11111);
                                        var msisdn = $('#msisdn').val();
                                        var password = $('#password').val();
                                        var telco = $(this).attr('data');
                                        if(typeof(telco)=="undefined" || telco.length < 1){
                                            $('.telcoGroup').after('<p class="text-danger">Please select mobile operators</p>');
                                            setTimeout(function(){
                                                $('.telcoGroup').next().remove();
                                            }, 3000);
                                            return false;
                                        }
                                        $.post("/sub/settelco", {"msisdn": msisdn,"password":password,"telco":telco},
                                            function (data) {
                                                if(data.status == 200){
                                                    var tip  = data.content;
                                                    $.myalert({
                                                        width: "50%",
                                                        content: '<b>'+tip+'</b>',
                                                        confirm_btn_click: function (e) { //确认按钮点击事件
                                                            $.myalert("getDialog").mydialog("hide");                                                           
                                                            //跳转首页
                                                            window.location.href='/';
                                                        }
                                                    });
                                                    // 关闭弹窗
                                                    $('#small-dialog').find('.mfp-close').trigger('click');
                                                }else if(data.status == 401){
                                                    $('#password').after('<p class="text-danger">'+data.content+'</p>');
                                                    setTimeout(function(){
                                                        $('#password').next().remove();
                                                    }, 3000);
                                                    return false;
                                                }
                                                console.log(data); //  2pm
                                            }, "json");

                                        
                                    });
                                });
                            </script>
                            <div class="forgot">
                                <a href="#">Forgot password ?</a>
                            </div>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="clearfix"> </div>
    </div>
</nav>
