<?php $this->display('layoutg/header.phtml'); ?>
<link href="/template/css/popup-box.css" rel="stylesheet" type="text/css" media="all" />
<!-- banner -->
<div class="sub-banner">
    <!-- Navbar -->
    <?php $this->display('layoutg/navbar.phtml'); ?>
</div>
<div class="events-w3layouts">
    <?php $this->display('layoutg/subscribe.phtml'); ?><br/>
    
    <a href="single.html"><div class="col-md-7 events-left-agile-agileits-w3layouts">
            <div class="events-text-w3-agile events-text1">
                <h4>June 20, 2017</h4>
                <p>Phasellus faucibus semper eros, quis mauris </p>
                <ul>
                    <li>by Admin</li>
                    <li><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> 10</li>
                </ul>
            </div>
        </div></a>
    <div class="col-md-5 events-right-agile">
        <a href="single.html"><div class="events-right-top">
                <div class="events-text-w3-agile events-text2">
                    <h4>July 20, 2017</h4>
                    <p>Aenean imperdiet volutpat tortor </p>
                    <ul>
                        <li>by Admin</li>
                        <li><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> 20</li>
                    </ul>
                </div>
            </div></a>
        <a href="single.html"><div class="events-right-bottom">
                <div class="events-text-w3-agile events-text2">
                    <h4>Aug 20, 2017</h4>
                    <p>Fusce aliquam purus  consectetur</p>
                    <ul>
                        <li>by Admin</li>
                        <li><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> 15</li>
                    </ul>
                </div>
            </div></a>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>

<div class="events-section2-agileinfo">
    <div class="container">
        <div class="blog1-w3ls">
            <div class="col-md-4 blog-image-w3l">
                <a href="single.html"><img src="/template/images/ng1.jpg" alt=" " /></a>
            </div>
            <div class="col-md-8 blog-text-w3ls">
                <a href="single.html"><h4>Quisque in lectus erat</h4></a>
                <div class="item_info">
                    <ul>
                        <li><a href="#"><i class="glyphicon glyphicon-user"></i>Admin</a></li>
                        <li><i class="glyphicon glyphicon-calendar"></i>14.May.2017</li>
                        <li><a href="#"><i class="glyphicon glyphicon-comment"></i>20 Comments</a></li>
                        <li><a href="#"><i class="glyphicon glyphicon-heart"></i>300 Likes</a></li>
                    </ul>				
                </div>
                <p>Aliquam suscipit neque massa, eu maximus felis gravida vel. Vestibulum lacinia risus risus, ut iaculis felis fermentum id. Cras at vulputate velit, vitae vestibulum augue. Etiam lorem nunc, mattis ac dignissim sit amet, varius et ex. Phasellus eleifend nibh justo, pulvinar cursus sapien commodo non.</p>
                <a href="single.html" class="blog-read" >Read More</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="blog2-w3ls">
            <div class="col-md-4 blog-image-w3l">
                <a href="single.html"><img src="/template/images/ng2.jpg" alt=" " /></a>
            </div>
            <div class="col-md-8 blog-text-w3ls">
                <a href="single.html"><h4>In finibus vel metus</h4></a>
                <div class="item_info">
                    <ul>
                        <li><a href="#"><i class="glyphicon glyphicon-user"></i>Admin</a></li>
                        <li><i class="glyphicon glyphicon-calendar"></i>17.Aug.2017</li>
                        <li><a href="#"><i class="glyphicon glyphicon-comment"></i>20 Comments</a></li>
                        <li><a href="#"><i class="glyphicon glyphicon-heart"></i>300 Likes</a></li>
                    </ul>				
                </div>
                <p>Aliquam suscipit neque massa, eu maximus felis gravida vel. Vestibulum lacinia risus risus, ut iaculis felis fermentum id. Cras at vulputate velit, vitae vestibulum augue. Etiam lorem nunc, mattis ac dignissim sit amet, varius et ex. Phasellus eleifend nibh justo, pulvinar cursus sapien commodo non.</p>
                <a href="single.html" class="blog-read" >Read More</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="blog3-w3ls">
            <div class="col-md-4 blog-image-w3l">
                <a href="single.html"><img src="/template/images/ng3.jpg" alt=" " /></a>
            </div>
            <div class="col-md-8 blog-text-w3ls">
                <a href="single.html"><h4>Nam eget ligula eu</h4></a>
                <div class="item_info">
                    <ul>
                        <li><a href="#"><i class="glyphicon glyphicon-user"></i>Admin</a></li>
                        <li><i class="glyphicon glyphicon-calendar"></i>24.Aug.2015</li>
                        <li><a href="#"><i class="glyphicon glyphicon-comment"></i>20 Comments</a></li>
                        <li><a href="#"><i class="glyphicon glyphicon-heart"></i>300 Likes</a></li>
                    </ul>				
                </div>
                <p>Aliquam suscipit neque massa, eu maximus felis gravida vel. Vestibulum lacinia risus risus, ut iaculis felis fermentum id. Cras at vulputate velit, vitae vestibulum augue. Etiam lorem nunc, mattis ac dignissim sit amet, varius et ex. Phasellus eleifend nibh justo, pulvinar cursus sapien commodo non.</p>
                <a href="single.html" class="blog-read" >Read More</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<?php $this->display('layoutg/footer.phtml'); ?>
</body>
</html>