<?php $this->display('layoutg/header.phtml'); ?>
<link href="/template/css/popup-box.css" rel="stylesheet" type="text/css" media="all" />
<!-- banner -->
<div class="sub-banner">
    <!-- Navbar -->
    <?php $this->display('layoutg/navbar.phtml'); ?>
</div>
<!-- gallery -->
<div class="gallery-w3layouts" id="gallery">
    <div class="container">
        <h2>Exclusive Games</h2>			
        <div class="gallery-grids">
            <div class="gallery-grid">
                <a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog">
                    <img src="/template/images/g1.jpg" alt=" " class="img-responsive zoom-img" />
                </a>
                <a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog2">
                    <img src="/template/images/g2.jpg" alt=" " class="img-responsive zoom-img" />
                </a>
            </div>
            <div class="gallery-grid">
                <a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog3">
                    <img src="/template/images/g3.jpg" alt=" " class="img-responsive zoom-img" />
                </a>
                <a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog4">
                    <img src="/template/images/g5.jpg" alt=" " class="img-responsive zoom-img" />
                </a>
            </div>
            <div class="gallery-grid">
                <a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog5">
                    <img src="/template/images/g6.jpg" alt=" " class="img-responsive zoom-img" />
                </a>
                <a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog6">
                    <img src="/template/images/g7.jpg" alt=" " class="img-responsive zoom-img" />
                </a>
            </div>
            <div class="gallery-grid">
                <a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog7">
                    <img src="/template/images/g4.jpg" alt=" " class="img-responsive zoom-img" />
                </a>
                <a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog8">
                    <img src="/template/images/g8.jpg" alt=" " class="img-responsive zoom-img" />
                </a>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!--//gallery -->
<script src="/template/js/jquery.magnific-popup.js" type="text/javascript"></script>
<script type="text/javascript" src="/template/js/modernizr.custom.53451.js"></script> 
<script>
    $(document).ready(function () {
        $('.popup-with-zoom-anim').magnificPopup({
            type: 'inline',
            fixedContentPos: false,
            fixedBgPos: true,
            overflowY: 'auto',
            closeBtnInside: true,
            preloader: false,
            midClick: true,
            removalDelay: 300,
            mainClass: 'my-mfp-zoom-in'
        });

    });
</script>	
<div class="pop-up"> 
    <div id="small-dialog" class="mfp-hide book-form">
        <div class="pop-up-content-agileits-w3layouts">
            <div class="col-md-6 w3ls-left">
                <img src="/template/images/g1.jpg" alt=" " class="img-responsive zoom-img" />
            </div>
            <div class="col-md-6 w3ls-right">
                <h4>Game-1</h4>
                <p>Duis sodales nibh vitae augue feugiat efficitur. Sed vel urna sollicitudin, interdum massa nec, sagittis massa. </p>
                <p class="agileits">Etiam porttitor neque enim, sit amet mollis est sollicitudin sed.</p>
                <div class="span span1">
                    <p class="left">NAME</p>
                    <p class="right">: Sed Perst</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span2">
                    <p class="left">DEVELOPER</p>
                    <p class="right">: Martina</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span3">
                    <p class="left">REQUIRES</p>
                    <p class="right">: 2GB Hard Disk Space</p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>		
<div class="pop-up"> 
    <div id="small-dialog2" class="mfp-hide book-form">
        <div class="pop-up-content-agileits-w3layouts">
            <div class="col-md-6 w3ls-left">
                <img src="/template/images/g2big.jpg" alt=" " class="img-responsive zoom-img" />
            </div>
            <div class="col-md-6 w3ls-right">
                <h4>Game-2</h4>
                <p>Duis sodales nibh vitae augue feugiat efficitur. Sed vel urna sollicitudin, interdum massa nec, sagittis massa. </p>
                <p class="agileits">Etiam porttitor neque enim, sit amet mollis est sollicitudin sed.</p>
                <div class="span span1">
                    <p class="left">NAME</p>
                    <p class="right">: Vivamus</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span2">
                    <p class="left">DEVELOPER</p>
                    <p class="right">: Quentin</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span3">
                    <p class="left">REQUIRES</p>
                    <p class="right">: 3GB Hard Disk Space</p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>	
<div class="pop-up"> 
    <div id="small-dialog3" class="mfp-hide book-form">
        <div class="pop-up-content-agileits-w3layouts">
            <div class="col-md-6 w3ls-left">
                <img src="/template/images/g3big.jpg" alt=" " class="img-responsive zoom-img" />
            </div>
            <div class="col-md-6 w3ls-right">
                <h4>Game-3</h4>
                <p>Duis sodales nibh vitae augue feugiat efficitur. Sed vel urna sollicitudin, interdum massa nec, sagittis massa. </p>
                <p class="agileits">Etiam porttitor neque enim, sit amet mollis est sollicitudin sed.</p>
                <div class="span span1">
                    <p class="left">NAME</p>
                    <p class="right">: Venenatis</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span2">
                    <p class="left">DEVELOPER</p>
                    <p class="right">: Stanley</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span3">
                    <p class="left">REQUIRES</p>
                    <p class="right">: 1GB Hard Disk Space</p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>	
<div class="pop-up"> 
    <div id="small-dialog4" class="mfp-hide book-form">
        <div class="pop-up-content-agileits-w3layouts">
            <div class="col-md-6 w3ls-left">
                <img src="/template/images/g5.jpg" alt=" " class="img-responsive zoom-img" />
            </div>
            <div class="col-md-6 w3ls-right">
                <h4>Game-4</h4>
                <p>Duis sodales nibh vitae augue feugiat efficitur. Sed vel urna sollicitudin, interdum massa nec, sagittis massa. </p>
                <p class="agileits">Etiam porttitor neque enim, sit amet mollis est sollicitudin sed.</p>
                <div class="span span1">
                    <p class="left">NAME</p>
                    <p class="right">: Interdum</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span2">
                    <p class="left">DEVELOPER</p>
                    <p class="right">: Spielberg</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span3">
                    <p class="left">REQUIRES</p>
                    <p class="right">: 3GB Hard Disk Space</p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>	
<div class="pop-up"> 
    <div id="small-dialog5" class="mfp-hide book-form">
        <div class="pop-up-content-agileits-w3layouts">
            <div class="col-md-6 w3ls-left">
                <img src="/template/images/g6.jpg" alt=" " class="img-responsive zoom-img" />
            </div>
            <div class="col-md-6 w3ls-right">
                <h4>Game-5</h4>
                <p>Duis sodales nibh vitae augue feugiat efficitur. Sed vel urna sollicitudin, interdum massa nec, sagittis massa. </p>
                <p class="agileits">Etiam porttitor neque enim, sit amet mollis est sollicitudin sed.</p>
                <div class="span span1">
                    <p class="left">NAME</p>
                    <p class="right">: Faucibus</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span2">
                    <p class="left">DEVELOPER</p>
                    <p class="right">: Cameron</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span3">
                    <p class="left">REQUIRES</p>
                    <p class="right">: 2GB Hard Disk Space</p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>	
<div class="pop-up"> 
    <div id="small-dialog6" class="mfp-hide book-form">
        <div class="pop-up-content-agileits-w3layouts">
            <div class="col-md-6 w3ls-left">
                <img src="/template/images/g7big.jpg" alt=" " class="img-responsive zoom-img" />
            </div>
            <div class="col-md-6 w3ls-right">
                <h4>Game-6</h4>
                <p>Duis sodales nibh vitae augue feugiat efficitur. Sed vel urna sollicitudin, interdum massa nec, sagittis massa. </p>
                <p class="agileits">Etiam porttitor neque enim, sit amet mollis est sollicitudin sed.</p>
                <div class="span span1">
                    <p class="left">NAME</p>
                    <p class="right">: Tincidunt</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span2">
                    <p class="left">DEVELOPER</p>
                    <p class="right">: Jackson</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span3">
                    <p class="left">REQUIRES</p>
                    <p class="right">: 4GB Hard Disk Space</p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>	
<div class="pop-up"> 
    <div id="small-dialog7" class="mfp-hide book-form">
        <div class="pop-up-content-agileits-w3layouts">
            <div class="col-md-6 w3ls-left">
                <img src="/template/images/g4big.jpg" alt=" " class="img-responsive zoom-img" />
            </div>
            <div class="col-md-6 w3ls-right">
                <h4>Game-7</h4>
                <p>Duis sodales nibh vitae augue feugiat efficitur. Sed vel urna sollicitudin, interdum massa nec, sagittis massa. </p>
                <p class="agileits">Etiam porttitor neque enim, sit amet mollis est sollicitudin sed.</p>
                <div class="span span1">
                    <p class="left">NAME</p>
                    <p class="right">: Vestibulum</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span2">
                    <p class="left">DEVELOPER</p>
                    <p class="right">: Daniel</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span3">
                    <p class="left">REQUIRES</p>
                    <p class="right">: 2GB Hard Disk Space</p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>	
<div class="pop-up"> 
    <div id="small-dialog8" class="mfp-hide book-form">
        <div class="pop-up-content-agileits-w3layouts">
            <div class="col-md-6 w3ls-left">
                <img src="/template/images/g8.jpg" alt=" " class="img-responsive zoom-img" />
            </div>
            <div class="col-md-6 w3ls-right">
                <h4>Game-8</h4>
                <p>Duis sodales nibh vitae augue feugiat efficitur. Sed vel urna sollicitudin, interdum massa nec, sagittis massa. </p>
                <p class="agileits">Etiam porttitor neque enim, sit amet mollis est sollicitudin sed.</p>
                <div class="span span1">
                    <p class="left">NAME</p>
                    <p class="right">: Vehicula ligula</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span2">
                    <p class="left">DEVELOPER</p>
                    <p class="right">: Cyrill</p>
                    <div class="clearfix"></div>
                </div>
                <div class="span span3">
                    <p class="left">REQUIRES</p>
                    <p class="right">: 3GB Hard Disk Space</p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>		
<?php $this->display('layoutg/footer.phtml'); ?>
</body>
</html>