<?php $this->display('layoutg/header.phtml'); ?>
        <!-- Header -->
        <div class="header">
            <!-- Navbar -->
            <?php $this->display('layoutg/navbar.phtml'); ?>
            <!-- //Navbar -->

            <!-- Slider -->
            <div class="slider">
                <ul class="rslides" id="slider">
                    <li>
                        <img src="/template/images/banner3.jpg" alt="" />
                    </li>
                    <li>
                        <img src="/template/images/banner2.jpg" alt="" />
                    </li>
                    <li>
                        <img src="/template/images/banner1.jpg" alt="" />
                    </li>
                </ul>
            </div>
            <!-- //Slider -->

        </div>
        <!-- Banner-Slider-JavaScript -->
        <script src="/template/js/responsiveslides.min.js"></script>
        <script>
            $(function () {
                $("#slider").responsiveSlides({
                    auto: true,
                    nav: true,
                    speed: 800,
                    namespace: "callbacks",
                    pager: true,
                });
            });
        </script>
        <!-- //Banner-Slider-JavaScript -->
        <!-- //Header -->

        <!-- trend -->
        <div class="trend-w3layouts">
            <div class="container">
                <h2>Trending Games</h2>
                <ul id="flexiselDemo1">			
                    <li>
                        <div class="trend-grid">
                            <h4>Racing Games</h4>
                            <img src="/template/images/tg1.jpg" alt=" " class="img-responsive" />
                        </div>
                    </li>
                    <li>
                        <div class="trend-grid">
                            <h4>3D Games</h4>
                            <img src="/template/images/tg2.jpg" alt=" " class="img-responsive" />
                        </div>
                    </li>
                    <li>
                        <div class="trend-grid">
                            <h4>Action Games</h4>
                            <img src="/template/images/tg3.jpg" alt=" " class="img-responsive" />
                        </div>
                    </li>
                    <li>
                        <div class="trend-grid">
                            <h4>Toy Games</h4>
                            <img src="/template/images/tg4.jpg" alt=" " class="img-responsive" />
                        </div>
                    </li>
                </ul>
                <script type="text/javascript">
                    $(window).load(function () {
                        $("#flexiselDemo1").flexisel({
                            visibleItems: 4,
                            animationSpeed: 1000,
                            autoPlay: true,
                            autoPlaySpeed: 3000,
                            pauseOnHover: true,
                            enableResponsiveBreakpoints: true,
                            responsiveBreakpoints: {
                                portrait: {
                                    changePoint: 480,
                                    visibleItems: 2
                                },
                                landscape: {
                                    changePoint: 640,
                                    visibleItems: 3
                                },
                                tablet: {
                                    changePoint: 768,
                                    visibleItems: 4
                                }
                            }
                        });

                    });
                </script>
                <script type="text/javascript" src="/template/js/jquery.flexisel.js"></script>
            </div>
        </div>
        <!-- //trend -->


        <!-- services-->
        <div class="services-agileits-w3layouts">
            <div class="container">
                <h3>Services</h3>
                <div class="col-md-3 service-grid-agileits service-grid-agileits-top">
                    <span class="glyphicon glyphicon-sort-by-attributes" aria-hidden="true"></span>
                    <h4>Quis tortor</h4>
                    <p>Curabitur suscipit porttitor aliquam. Etiam id placerat purus. Integer sodales elit eget arcu placerat.</p>
                    <a href="single.html">Read More</a>
                </div>
                <div class="col-md-3 service-grid-agileits">
                    <span class="glyphicon glyphicon-random" aria-hidden="true"></span>
                    <h4>Eget arcu</h4>
                    <p>Curabitur suscipit porttitor aliquam. Etiam id placerat purus. Integer sodales elit eget arcu placerat.</p>
                    <a href="single.html">Read More</a>
                </div>
                <div class="col-md-3 service-grid-agileits service-grid-agileits-bottom">
                    <span class="glyphicon glyphicon-yen" aria-hidden="true"></span>
                    <h4>Risus porta</h4>
                    <p>Curabitur suscipit porttitor aliquam. Etiam id placerat purus. Integer sodales elit eget arcu placerat.</p>
                    <a href="single.html">Read More</a>
                </div>
                <div class="col-md-3 service-grid-agileits service-grid-agileits-bottom">
                    <span class="glyphicon glyphicon-object-align-right" aria-hidden="true"></span>
                    <h4>Proin sapien</h4>
                    <p>Curabitur suscipit porttitor aliquam. Etiam id placerat purus. Integer sodales elit eget arcu placerat.</p>
                    <a href="single.html">Read More</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- //services-->

        <!-- new games -->
        <div class="new-w3-agile">
            <div class="container">
                <h3>New Games</h3>
                <div class="col-md-3 new-grid-w3l view view-eighth">
                    <img src="/template/images/ng1.jpg" alt=" " />
                    <div class="mask">
                        <a href="single.html"><h4>Click here</h4></a>
                        <p>To learn more about this</p>
                    </div>
                </div>
                <div class="col-md-3 new-grid-w3l view view-eighth">
                    <img src="/template/images/ng2.jpg" alt=" " />
                    <div class="mask">
                        <a href="single.html"><h4>Click here</h4></a>
                        <p>To learn more about this</p>
                    </div>
                </div>
                <div class="col-md-3 new-grid-w3l view view-eighth">
                    <img src="/template/images/ng3.jpg" alt=" " />
                    <div class="mask">
                        <a href="single.html"><h4>Click here</h4></a>
                        <p>To learn more about this</p>
                    </div>
                </div>
                <div class="col-md-3 new-grid-w3l view view-eighth">
                    <img src="/template/images/ng4.jpg" alt=" " />
                    <div class="mask">
                        <a href="single.html"><h4>Click here</h4></a>
                        <p>To learn more about this</p>
                    </div>
                </div>
                <div class="col-md-3 new-grid-agile view view-eighth">
                    <img src="/template/images/ng5.jpg" alt=" " />
                    <div class="mask">
                        <a href="single.html"><h4>Click here</h4></a>
                        <p>To learn more about this</p>
                    </div>
                </div>
                <div class="col-md-3 new-grid-agile view view-eighth">
                    <img src="/template/images/ng6.jpg" alt=" " />
                    <div class="mask">
                        <a href="single.html"><h4>Click here</h4></a>
                        <p>To learn more about this</p>
                    </div>
                </div>
                <div class="col-md-3 new-grid-agile view view-eighth">
                    <img src="/template/images/ng7.jpg" alt=" " />
                    <div class="mask">
                        <a href="single.html"><h4>Click here</h4></a>
                        <p>To learn more about this</p>
                    </div>
                </div>
                <div class="col-md-3 new-grid-agile view view-eighth">
                    <img src="/template/images/ng8.jpg" alt=" " />
                    <div class="mask">
                        <a href="single.html"><h4>Click here</h4></a>
                        <p>To learn more about this</p>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- //new games-->



        <div class="services-bottom-w3-agileits">
            <div class="container">
                <div class="wthree_info">
                    <section class="slider">
                        <div class="flexslider">
                            <ul class="slides">
                                <li>
                                    <div class="wthree_info_grid">
                                        <h3>Duis aute dolor reprehenderit</h3>
                                        <p>Excepteur sint occaecat cupidatat non proident, sunt officia.</p>
                                        <a href="single.html" class="learn">Learn More</a>
                                    </div>
                                </li>
                                <li>
                                    <div class="wthree_info_grid">
                                        <h3>Aliquip commodo consequat</h3>
                                        <p>Curabitur lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                        <a href="single.html" class="learn">Learn More</a>
                                    </div>
                                </li>
                                <li>
                                    <div class="wthree_info_grid">
                                        <h3>Quis autem vel eum iure ea</h3>
                                        <p>Phasellus ornare consectetur erat, eu vehicula orci finibus at.</p>
                                        <a href="single.html" class="learn">Learn More</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </section>
                    <!-- flexSlider -->

                    <script defer src="/template/js/jquery.flexslider.js"></script>
                    <script type="text/javascript">
                        $(window).load(function () {
                            $('.flexslider').flexslider({
                                animation: "slide",
                                start: function (slider) {
                                    $('body').removeClass('loading');
                                }
                            });
                        });
                    </script>
                    <!-- //flexSlider -->
                </div>
            </div>
        </div>

        <!-- footer -->
        <?php $this->display('layoutg/footer.phtml'); ?>
        <!-- //footer -->
    </body>
</html>