<?php $this->display('layoutg/header.phtml'); ?>
<link href="/template/css/popup-box.css" rel="stylesheet" type="text/css" media="all" />
<!-- banner -->
<div class="sub-banner">
    <!-- Navbar -->
    <?php $this->display('layoutg/navbar.phtml'); ?>
</div>
<!-- about-->
<div class="about-agileinfo" id="about">
    <div class="container">
        <?php $this->display('layoutg/subscribe.phtml'); ?>
        <div class="about-grids-w3-agileits">
            <div class="col-md-6 about-grid-left-agileits-w3layouts">
                <ul>
                    <li><i>1.</i><a class="link link--kumya" href="single.html"><span data-letters="Qui ratione voluptatem dolores eos qui">Qui ratione voluptatem dolores</span></a></li>
                    <li><i>2.</i><a class="link link--kumya" href="single.html"><span data-letters="Dolores eos qui ratione voluptatem sequi">Dolores eos qui ratione volu</span></a></li>
                    <li><i>3.</i><a class="link link--kumya" href="single.html"><span data-letters="Voluptatem quia voluptas sit asper">Voluptatem quia voluptas sit asper</span></a></li>
                    <li><i>4.</i><a class="link link--kumya" href="single.html"><span data-letters="Consectetur adipiscing elit, incid">Consectetur adipiscing elit, incid</span></a></li>
                    <li><i>5.</i><a class="link link--kumya" href="single.html"><span data-letters="Quia voluptas sit aspernatur aut odit">Quia voluptas sit aspernatur aut</span></a></li>
                    <li><i>6.</i><a class="link link--kumya" href="single.html"><span data-letters="Eos qui ratione voluptatem sequi">Eos qui ratione voluptatem sequi</span></a></li>
                </ul>
            </div>
            <div class="col-md-6 about-grid-right-w3-agile">
                <div class="grid-w3ls">
                    <figure class="effect-zoe">
                        <img src="/template/images/about.jpg" alt=" " class="img-responsive" />
                        <figcaption>
                            <h3>Games<span>Zone</span></h3>
                            <p class="icon-links">
                                <a href="#"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></a>
                                <a href="#"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
                                <a href="#"><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span></a>
                            </p>
                            <p class="description">Suspendisse convallis malesuada libero, non rutrum arcu pellentesque lacinia.</p>
                        </figcaption>			
                    </figure>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //about -->

<!-- Collection -->
<div class="collection-agileits">
    <div class="collection-grids-agileits-w3layouts">
        <div class="col-md-4 col-sm-4 collection-left">

        </div>
        <div class="col-md-8 col-sm-8 collection-right">
            <div class="col-md-4 col-sm-4 collection-grid collection-text collection-grid-1">
                <img src="/template/images/c1.png" alt="">
                <h3>Convallis </h3>
                <p>A elementum ligula lacus ac quam ultrices a scelerisque praesent vel suspendisse scelerisque.</p>
            </div>
            <div class="col-md-4 col-sm-4 collection-grid collection-image collection-grid-2">

            </div>
            <div class="col-md-4 col-sm-4 collection-grid collection-text collection-grid-3">
                <img src="/template/images/c2.png" alt="" />
                <h3>Lacinia</h3>
                <p>A elementum ligula lacus ac quam ultrices a scelerisque praesent vel suspendisse scelerisque.</p>
            </div>
            <div class="col-md-4 col-sm-4 collection-grid collection-image collection-grid-4">

            </div>
            <div class="col-md-4 col-sm-4 collection-grid collection-text collection-grid-5">
                <img src="/template/images/c3.png" alt="" />
                <h3>Sapien</h3>
                <p>A elementum ligula lacus ac quam ultrices a scelerisque praesent vel suspendisse scelerisque.</p>
            </div>
            <div class="col-md-4 col-sm-4 collection-grid collection-image collection-grid-6">

            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- //Collection -->


<!-- team -->
<div class="team-w3layouts">
    <div class="container">
        <h3>Our Team</h3>
        <div class="w3l_team_grids-agile">
            <div class="col-md-3 w3l_team_grid">
                <div class="view view-second">
                    <img src="/template/images/t1.jpg" alt=" " class="img-responsive" />
                    <div class="mask"></div>
                    <div class="content">
                        <div class="w3l_social_icons w3l_social_icons1">
                            <ul>
                                <li><a href="#" class="linkedin"></a></li>
                                <li><a href="#" class="google"></a></li>
                                <li><a href="#" class="twitter"></a></li>
                                <li><a href="#" class="facebook"></a></li>
                            </ul>
                        </div>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
                    </div>
                </div>
                <h4>Mariya Thomas</h4>
                <p>Games Designer</p>
            </div>
            <div class="col-md-3 w3l_team_grid">
                <div class="view view-second">
                    <img src="/template/images/t2.jpg" alt=" " class="img-responsive" />
                    <div class="mask"></div>
                    <div class="content">
                        <div class="w3l_social_icons w3l_social_icons1">
                            <ul>
                                <li><a href="#" class="linkedin"></a></li>
                                <li><a href="#" class="google"></a></li>
                                <li><a href="#" class="twitter"></a></li>
                                <li><a href="#" class="facebook"></a></li>
                            </ul>
                        </div>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
                    </div>
                </div>
                <h4>Dino Jass</h4>
                <p>Games Designer</p>
            </div>
            <div class="col-md-3 w3l_team_grid">
                <div class="view view-second">
                    <img src="/template/images/t3.jpg" alt=" " class="img-responsive" />
                    <div class="mask"></div>
                    <div class="content">
                        <div class="w3l_social_icons w3l_social_icons1">
                            <ul>
                                <li><a href="#" class="linkedin"></a></li>
                                <li><a href="#" class="google"></a></li>
                                <li><a href="#" class="twitter"></a></li>
                                <li><a href="#" class="facebook"></a></li>
                            </ul>
                        </div>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
                    </div>
                </div>
                <h4>Michael Doe</h4>
                <p>Games Designer</p>
            </div>
            <div class="col-md-3 w3l_team_grid">
                <div class="view view-second">
                    <img src="/template/images/t4.jpg" alt=" " class="img-responsive" />
                    <div class="mask"></div>
                    <div class="content">
                        <div class="w3l_social_icons w3l_social_icons1">
                            <ul>
                                <li><a href="#" class="linkedin"></a></li>
                                <li><a href="#" class="google"></a></li>
                                <li><a href="#" class="twitter"></a></li>
                                <li><a href="#" class="facebook"></a></li>
                            </ul>
                        </div>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
                    </div>
                </div>
                <h4>Rita James</h4>
                <p>Games Designer</p>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //team -->


<?php $this->display('layoutg/footer.phtml'); ?>
</body>
</html>