<?php $this->display('layouts/header.phtml'); ?>
<?php $this->display('layouts/navbar.phtml'); ?>
<?php $this->display('layouts/sidebar.phtml'); ?>
<div class="show-top-grids">
    <div class="main-grids about-main-grids">
        <div class="recommended-info">
            <h3>HƯỚNG DẪN</h3>
            <div class="about-grids">
                <div class="about-grids">
                    <div class="about-bottom-grids">
                        <div class="col-sm-12 about-left">
                            <div class="panel panel-default" style="text-align:left;">
                                <div class="panel-heading">
                                    <h4 class="panel-title">HƯỚNG DẪN</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                        <div class="panel panel-default">
                                            <div class="panel-heading" role="tab" id="headingOne">
                                                <h4 class="panel-title">
                                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" class="collapsed">
                                                        Đối tượng và điều kiện sử dụng
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" aria-expanded="false" >
                                                <div class="panel-body">
                                                    <ul>
                                                        <li>•	Là thuê bao Viettel đang hoạt động hai chiều</li>
                                                        <li>•	Điện thoại 3G/4G có kết nối GPRS/EDGE/3G/4G</li>
                                                        <li>•	Điện thoại, máy tính bảng có tính năng streaming/tải video.</li>

                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel panel-default">
                                            <div class="panel-heading" role="tab" id="headingTwo">
                                                <h4 class="panel-title">
                                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                                        Đăng ký dịch vụ 
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false">
                                                <div class="panel-body">
                                                    <h4><b>Một số cú pháp sử dụng dịch vụ:</b></h4>
                                                    <div class="bs-example" data-example-id="bordered-table">
                                                        <table class="table table-bordered">
                                                            <thead>
                                                                <tr>
                                                                    <th>STT</th>
                                                                    <th>Nội dung</th>
                                                                    <th>Nội dung SMS gửi 9067</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <tr>
                                                                    <th scope="row">1</th>
                                                                    <td>Đăng ký gói ngày</td>
                                                                    <th>DK1</th>
                                                                </tr>
                                                                <tr>
                                                                    <th scope="row">2</th>
                                                                    <td>Đăng ký gói tuần</td>
                                                                    <th>DK7</th>
                                                                </tr>
                                                                <tr>
                                                                    <th scope="row">3</th>
                                                                    <td>Nhận HDSD</td>
                                                                    <th>HD</th>
                                                                </tr>
                                                                <tr>
                                                                    <th scope="row">4</th>
                                                                    <td>Kiểm tra gói cước đang sử dụng</td>
                                                                    <th>KT</th>
                                                                </tr>
                                                                <tr>
                                                                    <th scope="row">5</th>
                                                                    <td>Lấy mật khẩu truy cập Wifi</td>
                                                                    <th>MK</th>
                                                                </tr>
                                                                <tr>
                                                                    <th scope="row">6</th>
                                                                    <td>Hủy gói cước</td>
                                                                    <th>HUY TênGói</th>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                    <h4><b>Để đăng ký gói cước bạn có thể làm theo các cách sau</b></h4>
                                                    <p>•	- Qua tin nhắn SMS: </p>
                                                    <p>Đăng ký gói ngày:  Soạn <span style="color:red">DK1</span> gửi <span style="color:red">5598</span></p>
                                                    <p>Đăng ký gói tuần:  Soạn <span style="color:red">DK7</span> gửi <span style="color:red">5598</span></p>


                                                    <p>•	- Qua Wapsite: </p>
                                                    <p>Bước 1: Bât <span style="color:red">3G</span>, truy cập wapsite http://gogoplay.vn </p>
                                                    <p>Bước 2: Chọn mục đăng ký</p>
                                                    <p>Bước 3: Chọn các gói cước và xác nhận việc đăng ký (Nếu không nhận diện thuê bao sử dụng cú pháp đăng ký qua SMS theo hướng dẫn)</p>

                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel panel-default">
                                            <div class="panel-heading" role="tab" id="headingThree">
                                                <h4 class="panel-title">
                                                    <a class="" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                                        Sử dụng dịch vụ 
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapseThree" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingThree" aria-expanded="false">
                                                <div class="panel-body">
                                                    <p>Dịch vụ hỗ trợ KH xem, thích, đánh giá, bình luận Video Clip... Để sử dụng dịch vụ bạn làm theo hướng dẫn sau:</p>
                                                    <h4><b>o	3.1 Sử dụng qua Wapsite</b></h4>
                                                    <p>•	- Sử dụng dịch vụ qua thiết bị di động vào bằng 3G</p>
                                                    <p><b>Bước 1: </b>Truy cập <a href="Truy cập http://gogoplay.vn ">http://gogoplay.vn </a></p>
                                                    <p><b>Bước 2: </b>Lựa chọn các nội dung phù hợp trên trang chủ, các danh mục hoặc sử dụng chức năng tìm kiếm để tìm các nội dung cần xem.</p>
                                                    <p><b>Bước 3: </b>Bấm vào nút Play để xem các clip.</p>
                                                    <p><b>Bước 4: </b>Hệ thống sẽ tự động tải và hiển thị nội dung trên màn hình.</p>

                                                    <p>•	- Sử dụng dịch vụ qua wifi</p>
                                                    <p><b>Bước 1: </b>Truy cập <a href="Truy cập http://gogoplay.vn ">http://gogoplay.vn </a></p>
                                                    <p><b>Bước 2: </b>Chọn đăng nhập bằng cách nhập số điện thoại và mật khẩu để sử dụng các dịch vụ.</p>
                                                    <p><b>Bước 3: </b>Lựa chọn các nội dung phù hợp trên trang chủ, các danh mục hoặc sử dụng chức năng tìm kiếm để tìm các nội dung cần xem.</p>
                                                    <p><b>Bước 4: </b>Bấm vào nút Play để xem các clip.</p>
                                                    <p><b>Bước 5: </b>Hệ thống sẽ tự động tải và hiển thị nội dung trên màn hình.</p>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="panel panel-default">
                                            <div class="panel-heading" role="tab" id="headingFour">
                                                <h4 class="panel-title">
                                                    <a class="" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseThree">
                                                        Giá cước 
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapseFour" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingThree" aria-expanded="false">
                                                <div class="panel-body">
                                                    <p>•	Cước gửi tin đến 5598: miễn phí</p>
                                                    <p>•	Cước gửi tin đến 5598: miễn phí</p>
                                                    <h4><b>Bảng giá cước dịch vụ:</b></h4>
                                                    <div class="bs-example" data-example-id="bordered-table">
                                                        <table class="table table-bordered">
                                                            <thead>
                                                                <tr>
                                                                    <th rowspan="2" style="text-align:center;">TT</th>
                                                                    <th rowspan="2" style="text-align:center;">Nội dung</th>
                                                                    <th>Giá cước</th>
                                                                </tr>
                                                                <tr>
                                                                    <th>Cước thuê bao</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <tr>
                                                                    <th scope="row">I</th>
                                                                    <td colspan="2" style="text-align:center;">Mua theo gói nội dung</td>
                                                                </tr>
                                                                <tr>
                                                                    <th scope="row">1</th>
                                                                    <td>Gói ngày – FUNNY VIDEO</td>
                                                                    <th>2.000đ/ngày, gia hạn hàng ngày</th>
                                                                </tr>
                                                                <tr>
                                                                    <th scope="row">2</th>
                                                                    <td>Gói tuần – FUNNY VIDEO</td>
                                                                    <th>7.000đ/ 7ngày, gia hạn hàng tuần</th>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                        <p>•	- Giá cước đã bao gồm 10% VAT.</p>

                                                        <p>•	- Toàn bộ cước của dịch vụ sẽ được ghi vào hóa đơn cước tháng (đối với thuê bao trả sau) và trừ vào tài khoản chính (đối với thuê bao trả trước).</p>

                                                        <p>•	- Ngay sau khi hết thời gian sử dụng, gói cước sẽ tự động gia hạn nếu khách hàng không yêu cầu hủy dịch vụ. Nếu việc trừ cước khi gia hạn gói cước trong vòng 30 ngày không thành công, hệ thống sẽ hủy gói cước của bạn.</p>
                                                        <p>•	- Đối với trường hợp KH hủy đi và đăng ký lại gói cước khi vẫn còn hiệu lực của lần ĐK trước: Miễn phí.</p>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="clearfix"> </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
<?php $this->display('layouts/footer.phtml'); ?>
<?php if ($applogin) { ?>
    <script src="/ckeditor/ckeditor.js"></script>
    <!--<script src="/ckeditor/samples/js/sample.js"></script>-->
    <script src="/assets/js/wap-ckeditor.js"></script>
    <script>
        initSample();
        // 保存内容  editor 是ckeditor的id或者名字
        var content = CKEDITOR.instances.editor.getData();
        if(content.length > 0){
            $('#content').click(function(){
                $.post("/video/use", { content: content ,cid : GetQueryString('c')},function(data){
                    console.log(data);
                });
            });
        }
        
        function GetQueryString(name)
        {
             var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
             var r = window.location.search.substr(1).match(reg);
             if(r!=null)return  unescape(r[2]); return null;
        }
    </script>
<?php } ?>


