<?php $this->display('layouts/header.phtml'); ?>
<?php $this->display('layouts/navbar.phtml'); ?>
<?php $this->display('layouts/sidebar.phtml'); ?>
<div class="show-top-grids">
    <div class="col-sm-10 show-grid-left main-grids">
        <?php if($contents){ foreach($contents as $key => $value){ ?>
        <div class="recommended" id="grid<?php echo $key?>">
            <div class="recommended-grids english-grid">
                <div class="recommended-info">
                    <div class="heading">
                        <h3><?php echo $group_menus[$key];?></h3>
                    </div>
                    <div class="heading-right">
                        <a  href="#small-dialog8" class="play-icon popup-with-zoom-anim">Subscribe</a>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <?php  foreach ($value as $kk => $vv){?>
                    <div class="col-md-3 resent-grid recommended-grid movie-video-grid">
                        <div class="resent-grid-img recommended-grid-img">
                            <a href="/index/show?id=<?php echo $vv['id'];?>"><img src="<?php echo $vv['thumb'];?>" alt="" /></a>
                            <div class="time small-time show-time movie-time">
                                <p><?php echo $vv['time_length']?></p>
                            </div>
                            <div class="clck movie-clock">
                                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="resent-grid-info recommended-grid-info recommended-grid-movie-info">
                            <h5><a href="/index/show?id=<?php echo $vv['id'];?>" class="title"><?php echo $vv['title'];?></a></h5>
                            <ul>
                                <li><p class="author author-info"><a href="#" class="author"><?php echo $vv['authorid'];?></a></p></li>
                                <li class="right-list"><p class="views views-info"><?php echo $vv['click'];?> views</p></li>
                            </ul>
                        </div>
                    </div>
                <?php }?>
            <div class="clearfix"> </div>
            </div>
        </div>
        <?php }}?>
        <center><?php echo $page;?></center>
    </div>
    <div class="col-md-2 show-grid-right">
        <h3>Upcoming Channels</h3>
        <?php if($category_top){ foreach ($category_top as $kk => $val){?>
        <div class="show-right-grids">
            <ul>
                <li class="tv-img"><a href="#"><img src="/assets/images/mv.png" alt="" /></a></li>
                <li><a href="/index/show?id=<?php echo $val['id']?>"><?php echo $val['title']?></a></li>
            </ul>
        </div>
        <?php }}?>
    </div>
    <div class="clearfix"> </div>
</div>
<?php $this->display('layouts/footer.phtml'); ?>

<script type="text/javascript">
    function GetQueryString(name)
    {
         var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
         var r = window.location.search.substr(1).match(reg);
         if(r!=null)return  unescape(r[2]); return null;
    }
    $(document).ready(function() {
        var pos = $('#grid'+GetQueryString('c'));
        $("html, body").animate({
            scrollTop: ((pos.offset().top)-100) +"px"
        }, {
            duration: 500,
            easing: "swing"
        });
    });

</script>

