<?php $this->display('layouts/header.phtml'); ?>
<?php $this->display('layouts/navbar.phtml'); ?>
<?php $this->display('layouts/sidebar.phtml'); ?>
<div class="show-top-grids">
    <div class="main-grids about-main-grids">
        <div class="recommended-info">
            <h3>Liên hệ</h3>
            <div class="about-grids">
                <div class="about-grids">
                    <div class="about-bottom-grids">
                        <div class="col-sm-12 about-left">
                            <div class="about-left-grids">
                                <div class="col-md-2 about-left-img">
                                    <span class="glyphicon glyphicon-user glyphicon-facetime-video" aria-hidden="true"></span>
                                </div>
                                <div class="col-md-10 about-left-info">
                                    <a href="#"> LIÊN HỆ TƯ VẤN HỖ TRỢ</a>
                                    <p>Tổng đài hỗ trợ khách hàng: 19009269 (1500đ/phút)<br/>
                                        Email: chamsockhachhang@bluepay.asia<br/>
                                        Thời gian làm việc: Từ 8h00 đến 18h00, từ thứ 2 đến thứ 6 hàng tuần.<br/>
                                        Công ty TNHH Công Nghệ Blue Mobile Việt Nam<br/>
                                        Địa chỉ: tầng 11 tòa nhà Oriental,324 Tây Sơn, Quận Đống Đa, Hà Nội<br/>
                                    </p>
                                </div>
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                        
                        <div class="clearfix"> </div>
                    </div>
                   
                </div>

            </div>
        </div>
    </div>
</div>
<?php //$this->display('layouts/footer.phtml'); ?>


