<?php $this->display('layouts/header.phtml'); ?>
<?php $this->display('layouts/navbar.phtml'); ?>
<?php $this->display('layouts/sidebar.phtml'); ?>
<div class="main-grids">
    <div class="show-top-grids">
        <div id="editor">
            <h1>Hello world!</h1>
        </div>
    </div>
</div>
<?php $this->display('layouts/footer.phtml'); ?>
<script src="/ckeditor/ckeditor.js"></script>
<!--<script src="/ckeditor/samples/js/sample.js"></script>-->
<script src="/assets/js/wap-ckeditor.js"></script>
<script>
    initSample();
</script>
