<?php $this->display('layouts/header.phtml'); ?>
<?php $this->display('layouts/navbar.phtml'); ?>
<?php $this->display('layouts/sidebar.phtml'); ?>
<div class="show-top-grids">
    <div class="main-grids news-main-grids">
        <div class="recommended-info">
            <h3>Điều khoản sử dụng</h3>
            <p class="history-text">Thỏa thuận sử dụng dv FUNNY VIDEO (<a href="http://gogoplay.vn">http://gogoplay.vn</a>)
            </p>
            <div class="terms-info">
                <div class="terms-info-grid">
                    <h3>I. Các nội dung cấm trao đổi, chia sẻ trên FUNNY VIDEO</h3>
                    <p></p>
                    <ol>
                        <li><p class="terms-info-text">Lợi dụng việc cung cấp, sử dụng dịch vụ Internet và thông tin trên mạng nhằm mục đích:</p>
                            <ol type="a">
                                <li><p class="terms-info-text">Chống lại Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam; gây phương hại đến an ninh quốc gia, trật tự an toàn xã hội; phá hoại khối đại đoàn kết dân tộc; tuyên truyền chiến tranh, khủng bố; gây hận thù, mâu thuẫn giữa các dân tộc, sắc tộc, tôn giáo;</p></li>

                                <li><p class="terms-info-text">Tuyên truyền, kích động bạo lực, dâm ô, đồi trụy, tội ác, tệ nạn xã hội, mê tín dị đoan, phá hoại thuần phong, mỹ tục của dân tộc;</p></li>

                                <li><p class="terms-info-text">Tiết lộ bí mật nhà nước, bí mật quân sự, an ninh, kinh tế, đối ngoại và những bí mật khác do pháp luật quy định;</p></li>

                                <li><p class="terms-info-text">Đưa thông tin xuyên tạc, vu khống, xúc phạm uy tín của tổ chức, danh dự và nhân phẩm của cá nhân;</p></li>

                                <li><p class="terms-info-text">Quảng cáo, tuyên truyền, mua bán hàng hóa, dịch vụ bị cấm; truyền bá tác phẩm báo chí, văn học, nghệ thuật, xuất bản phẩm bị cấm;</p></li>

                                <li><p class="terms-info-text">Giả mạo tổ chức, cá nhân và phát tán thông tin giả mạo, thông tin sai sự thật xâm hại đến quyền và lợi ích hợp pháp của tổ chức, cá nhân.</p></li>

                                <li><p class="terms-info-text">Tự ý đưa nội dung vi phạm các quy định không thuộc quyền sở hữu của mình mà không được sự cho phép của người chủ sở hữu đích thực.</p></li>

                            </ol>
                        </li>
                        <li><p class="terms-info-text">Cản trở trái pháp luật việc cung cấp và truy cập thông tin hợp pháp, việc cung cấp và sử dụng các dịch vụ hợp pháp trên Internet của tổ chức, cá nhân.</p>
                        </li>
                        <li><p class="terms-info-text"> Cản trở trái pháp luật hoạt động của hệ thống máy chủ tên miền quốc gia Việt Nam ".vn", hoạt động hợp pháp của hệ thống thiết bị cung cấp dịch vụ Internet và thông tin trên mạng.</p>
                        </li>
                        <li><p class="terms-info-text">Sử dụng trái phép mật khẩu, khóa mật mã của tổ chức, cá nhân; thông tin riêng, thông tin cá nhân và tài nguyên Internet.</p>
                        </li>
                        <li><p class="terms-info-text"> Tạo đường dẫn trái phép đối với tên miền hợp pháp của tổ chức, cá nhân; tạo, cài đặt, phát tán phần mềm độc hại, vi-rút máy tính; xâm nhập trái phép, chiếm quyền điều khiển hệ thống thông tin, tạo lập công cụ tấn công trên Internet.</p>
                        </li>
                    </ol>
                </div>
                <div class="terms-info-grid">
                    <h3>II. Quyền, trách nhiệm của người sử dụng dịch vụ FUNNY VIDEO</h3>
                    <p></p>
                    <ol type="A">
                        <li><p class="terms-info-text">Quyền</p>
                            <ol>
                                <li><p class="terms-info-text">Dịch vụ FUNNY VIDEO cho phép các thành viên được sử dụng các chức năng của mạng xã hội như đăng thông tin, chia sẽ thông tin. Người dùng được tự do sử dụng dịch vụ miễn rằng không vi phạm các thỏa thuận sử dụng dich vụ.</p></li>
                                <li><p class="terms-info-text">Tất cả các thông tin nếu người dùng không muốn chia sẻ công khai thì sẽ được bảo mật tuyệt đối. Chúng tôi chỉ cung cấp thông tin khi có yêu cầu hợp pháp từ các cơ quan quản lý pháp luật có thẩm quyền.</p></li>
                                <li><p class="terms-info-text">Dịch vụ FUNNY VIDEO sẽ đăng tải các nội dung trên website gogoplay.vn nên có thể có việc sao chép bản quyền bất hợp pháp. Các thành viên cần cân nhắc trước khi đăng nội dung.</p></li>
                            </ol>
                        </li>
                        <li><p class="terms-info-text">Trách nhiệm</p>
                            <ol>
                                <li><p class="terms-info-text">Bạn phải đủ từ 14 tuổi trở lên mới tham gia mạng xã hội của chúng tôi. Trách nhiệm đầu tiên là bạn phải tuân thủ các điều cấm trao đổi chia sẻ trên mạng xã hội FUNNY VIDEO theo mục I thỏa thuận này.</p></li>

                                <li><p class="terms-info-text">Nhằm phát triển FUNNY VIDEO một cách đúng luật, các thành viên có trách nhiệm gửi cho chúng tôi báo cáo vi phạm của các thành viên khác để chúng tôi phát hiện nhanh chóng và xử lý kịp thời.</p></li>

                                <li><p class="terms-info-text">Bạn cũng có trách nhiệm cân nhắc các chính sách mà chúng tôi thay đổi, bổ sung. Bạn hãy kiểm tra email (Tài khoản cá nhân) thường xuyên để biết các thay đổi nếu có. Chỉ khi bạn đồng ý với sự thay đổi thì mới tiếp tục sử dụng dịch vụ.</p></li>

                                <li><p class="terms-info-text">Bạn có trách nhiệm phải chấp hành các yêu cầu cung cấp thông tin trong khuôn khổ của pháp luật theo yêu cầu của cơ quan quản lý pháp luật có thẩm quyền.</p></li>

                                <li><p class="terms-info-text">Chúng tôi có thể xóa mọi nội dung hoặc thông tin bạn đăng trên FUNNY VIDEO nếu chúng tôi tin rằng nội dung hoặc thông tin đó vi phạm Tuyên bố này hay chính sách của chúng tôi. Nếu chúng tôi xóa nội dung của bạn vì vi phạm bản quyền của người khác và bạn tin là chúng tôi đã sai khi xóa nội dung đó, chúng tôi sẽ cho bạn cơ hội khiếu nại.</p></li>

                                <li><p class="terms-info-text">Nếu bạn liên tục vi phạm quyền sở hữu trí tuệ hoặc chính sách khác đã thỏa thuận quá 2 lần, chúng tôi sẽ vô hiệu tài khoản của bạn.</p></li>

                                <li><p class="terms-info-text">Bạn sẽ không đăng giấy tờ nhận dạng hoặc thông tin tài chính nhạy cảm của bất kỳ ai trên FUNNY VIDEO.</p></li>
                            </ol>
                        </li>
                    </ol>
                </div>
                <div class="terms-info-grid">
                    <h3>III. Quyền, trách nhiệm của doanh nghiệp thiết lập dịch vụ FUNNY VIDEO.</h3>
                    <p></p>
                    <ol type="A">
                        <li><p class="terms-info-text">Quyền</p>
                            <ol>
                                <li><p class="terms-info-text">Có quyền áp dụng các quy định về điều khoản sử dụng dịch vụ cung cấp mà không cần phải thông báo trước cho thành viên.</p></li> 

                                <li><p class="terms-info-text">Nếu bạn vi phạm thỏa thuận sử dụng thì chúng tôi có quyền áp dụng các biện pháp chế tài theo như điều khoản và thỏa thuận sử dụng này như gỡ bỏ, xóa nội dung vi phạm, xóa tài khoản truy cập và chúng tôi có quyền phối hợp cung cấp thông tin cá nhân bạn theo yêu cầu của cơ quan nhà nước có thẩm quyền.</p></li> 

                                <li><p class="terms-info-text">Chúng tôi có quyền thương mại hóa dịch vụ FUNNY VIDEO, tuy nhiên chúng tôi tuyệt đối tuân thủ thỏa thuận này. Chúng tôi tuyệt đối không bán lại nội dung, thông tin của thành viên.</p></li> 

                                <li><p class="terms-info-text">Chúng tôi có quyền nâng cấp hệ thống để phục vụ tốt hơn. Quá trình nâng cấp có thể làm gián đoạn việc sử dụng dịch vụ hoặc chất lượng dịch vụ không đảm bảo trong thời điểm nâng cấp.</p></li> 

                                <li><p class="terms-info-text">Trong trường hợp xấu nhất vì hoạt động của dich vụ FUNNY VIDEO không hiệu quả, buộc lòng chúng tôi phải đóng dịch vụ, khi đó chúng tôi sẽ báo trước cho các bạn tối thiểu trước 06 tháng. Chúng tôi cũng phải buộc phải tạm dừng, đóng cửa dịch vụ theo đề nghị của cơ quan pháp luật. Chúng tôi không phải bồi thường cho các hành động này.</p></li> 

                                <li><p class="terms-info-text">Chúng tôi được miễn trừ trách nhiện về nội dung mà các bạn đăng tải lên dịch vụ khi sảy ra khiếu nại, tranh chấp về bản quyền đối với bên thứ 3 hoặc trước pháp luật.</p></li>  
                            </ol>
                        </li>
                        <li><p class="terms-info-text"> Trách nhiệm
                            </p>
                            <ol>
                                <li><p class="terms-info-text">Trách nhiệm chúng tôi là phải tuân thủ các điều khoản và thỏa thuận sử dụng này một cách nghiêm túc. Chúng tôi có trách nhiệm xây dựng và vận hành hệ thống đảm bảo an toàn và an ninh thông tin.</p></li>

                                <li><p class="terms-info-text">Chúng tôi có trách nhiệm đảm bảo không hạn chế quyền sở hữu, quản lý hợp pháp của các bạn khi thông tin chia sẽ trên mạng xã hội FUNNY VIDEO.</p></li>

                                <li><p class="terms-info-text">Chúng tôi có trách nhiệm thông báo cho bạn biết các thay đổi về điều khoản và thỏa thuận. Bạn phải đồng ý thì chúng tôi mới áp dụng các điều khoản và chính sách mới. Việc thông báo chính sách mới nếu có sẽ được thực hiện thông qua email hoặc các pop up khi bạn truy cập website http://gogoplay.vn hoặc hiển thị trên tường trang đăng nhập của bạn.</p></li>

                                <li><p class="terms-info-text">Chúng tôi có trách nhiệm thông báo cho bạn biết các vi phạm của bạn, tuy nhiên chúng tôi không chờ bạn phản hồi. Chúng tôi buộc lòng phải gỡ bỏ, xóa các nội dung mà chúng tôi có đầy đủ chứng cứ chứng minh bạn đã vi phạm pháp luật, vi phạm các chính sách và điều khoản thỏa thuận sử dụng này. Bạn có quyền khiếu nại về các quyết định của chúng tôi.</p></li>

                                <li><p class="terms-info-text">Chúng tôi đảm bảo bảo mật các thông tin mà bạn không muốn công khai theo chọn lựa của bạn, trừ khi theo yêu cầu của cơ quan pháp luật có thẩm quyền.</p></li>

                                <li><p class="terms-info-text">Chúng tôi có trách nhiệm xây dựng hệ thống, lưu trữ thông tin đáp ứng các yêu cầu của Bộ Thông tin và Truyền thông. Chấp hành công tác thanh tra định lỳ hoặc đột xuất. Chịu trách nhiệm bồi thường thiệt hại, phạt vi phạm do các hành vi vi phạm pháp luật của mình (nếu có) gây ra và chúng tôi không yêu cầu chia sẻ các khoản chi phí này cho các thành viên sử dụng mạng xã hội.</p></li>
                            </ol>
                        </li>
                    </ol>
                </div>
                <div class="terms-info-grid">
                    <h3>IV. Cơ chế xử lý đối với thành viên vi phạm thỏa thuận cung cấp và sử dụng dịch vụ FUNNY VIDEO</h3>
                    <p></p>
                    <ol>
                        <li><p class="terms-info-text">Nếu bạn vi phạm điều khoản quy định về thỏa thuận cung cấp và sử dụng dịch vụ hoặc theo cách khác tạo rủi ro hoặc trách nhiệm pháp lý có thể cho chúng tôi, chúng tôi có thể gửi thông báo cảnh báo nội dung vi phạm và yêu cầu bạn ngay lập tức gỡ bỏ nội dung vi phạm đó. Nếu bạn không gỡ bỏ nội dung vi phạm, chúng tôi sẽ gỡ bỏ, xóa nội dung hoặc buộc sẽ khóa tài khoản của bạn. Nếu bạn vi phạm 02 lần chúng tôi buộc lòng xóa vĩnh viễn tài khoản bạn. Đồng thời chúng tôi sẽ thông báo cho bạn qua email của bạn. Bạn cũng có thể xóa tài khoản của mình hoặc làm vô hiệu ứng dụng của mình bất kỳ lúc nào.
                            </p>
                        </li>
                    </ol>
                </div>
                <div class="terms-info-grid">
                    <h3>V. Các rủi ro khi lưu trữ, trao đổi và chia sẻ thông tin trên dịch vụ FUNNY VIDEO.</h3>
                    <p></p>
                    <ol>
                        <li><p class="terms-info-text">Chia sẻ nội dung và thông tin của bạn</p>
                            <ol>
                                <li><p class="terms-info-text">Bạn sở hữu tất cả các nội dung và thông tin bạn đăng trên FUNNY VIDEO và bạn có thể kiểm soát việc chia sẻ thông tin đó thông qua thông tin cá nhân và cập nhật thông tin cá nhân. Ngoài ra:</p></li>
                                <ol type="i">
                                    <li><p class="terms-info-text">Đối với những nội dung ảnh số có quyền sở hữu trí tuệ (nội dung IP), bạn mặc định cho chúng tôi bản quyền của bạn: bạn cấp cho chúng tôi một giấy phép không độc quyền, có thể chuyển nhượng, có thể cấp phép lại, miễn phí, toàn cầu để sử dụng mọi nội dung IP mà bạn đăng trên hoặc liên quan tới FUNNY VIDEO.</p></li>

                                    <li><p class="terms-info-text">Khi bạn xóa nội dung IP, thao tác đó tương tự như làm rỗng thùng rác trên máy tính. Tuy nhiên, bạn hiểu rằng nội dung bị xóa có thể vẫn còn trong các bản sao lưu trong một khoảng thời gian hợp lý (nhưng sẽ không khả dụng với những người khác).</p></li>

                                    <li><p class="terms-info-text">Khi bạn công bố nội dung hoặc thông tin bằng cách điền thông tin cá nhân hoặc cập nhật thông tin cá nhân, có nghĩa là bạn đang cho phép mọi người bao gồm những người là thành viên của FUNNY VIDEO, truy cập, sử dụng thông tin đó.</p></li>

                                    <li><p class="terms-info-text">Chúng tôi luôn tiếp nhận phản hồi hoặc các đề xuất khác của bạn về FUNNY VIDEO nhưng bạn cần hiểu rằng chúng tôi có thể sử dụng các phản hồi và đề xuất đó mà không có nghĩa vụ phải đền bù cho bạn (cũng như bạn không có nghĩa vụ phải cung cấp các phản hồi và đề xuất đó).</p></li>
                                </ol>
                            </ol>

                        </li>

                        <li><p class="terms-info-text">An toàn</p>
                            <ol>
                                <li><p class="terms-info-text">Chúng tôi nỗ lực hết sức mình để tạo an toàn cho FUNNY VIDEO nhưng chúng tôi không thể đảm bảo điều đó. Chúng tôi cần sự giúp đỡ của bạn để tạo an toàn cho FUNNY VIDEO, với các cam kết sau từ phía bạn:</p>
                                    <ol type="i">
                                        <li><p class="terms-info-text">Bạn sẽ không vi phạm quy định như spam trên FUNNY VIDEO.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không tham gia vào hoạt động tiếp thị bất hợp pháp như quảng cáo đồi trụy… trên FUNNY VIDEO.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không tải lên virus hoặc mã độc hại khác.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không hack thông tin đăng nhập hoặc tài khoản của người khác.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không hăm dọa hoặc quấy rối bất kỳ người dùng nào.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không đăng nội dung: có ngôn từ kích động thù địch, mang tính đe dọa hay khiêu dâm; kích động bạo lực hoặc chứa ảnh khỏa thân hoặc hình ảnh bạo lực hay nội dung bạo lực vô cớ.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không dùng FUNNY VIDEO để làm bất kỳ điều gì bất hợp pháp, sai trái, độc hại hoặc phân biệt đối xử.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không làm bất kỳ điều gì có thể làm vô hiệu, quá tải hoặc ảnh hưởng đến hệ thống của FUNNY VIDEO.</p></li>
                                    </ol>
                                </li>
                            </ol>
                        </li>

                        <li><p class="terms-info-text">Đăng ký và bảo mật tài khoản</p>
                            <ol>
                                <li><p class="terms-info-text">Người dùng FUNNY VIDEO phải cung cấp đầy đủ thông tin bắt buộc khi đăng ký tài khoản Sau đây là một số cam kết của bạn đối với chúng tôi liên quan đến việc đăng ký và duy trì bảo mật tài khoản của bạn:</p>
                                    <ol type="i">
                                        <li><p class="terms-info-text">Bạn sẽ không cung cấp mọi thông tin cá nhân sai lệch trên FUNNY VIDEO hoặc tạo tài khoản cho bất kỳ ai khác ngoài bạn mà không được phép.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không tạo nhiều hơn một tài khoản cá nhân.</p></li>

                                        <li><p class="terms-info-text">Nếu chúng tôi vô hiệu tài khoản của bạn, bạn sẽ không tạo một tài khoản khác mà không có sự cho phép của chúng tôi.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không dùng FUNNY VIDEO nếu bạn dưới 14 tuổi.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ duy trì thông tin liên hệ của mình chính xác và cập nhật.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không chia sẻ mật khẩu của mình, không cho bất kỳ ai truy cập vào tài khoản của mình hoặc làm bất kỳ điều gì có thể gây nguy hiểm cho việc bảo mật tài khoản của mình.</p></li>

                                        <li><p class="terms-info-text">Bạn sẽ không chuyển nhượng tài khoản (bao gồm mọi Trang) cho bất kỳ ai mà không có văn bản cho phép trước hết của chúng tôi.</p></li>
                                    </ol>
                                </li>
                                <li><p class="terms-info-text">Nếu bạn chọn một tên người dùng hoặc tên định danh tương tự cho tài khoản hoặc Trang của bạn, chúng tôi bảo lưu quyền xóa hoặc xác nhận lại tên đó nếu chúng tôi tin là phù hợp (chẳng hạn như khi chủ sở hữu thương hiệu phàn nàn về tên người dùng không liên quan chặt chẽ tới tên thật của người dùng).</p></li>
                            </ol>
                        </li>
                    </ol>
                </div>
                <div class="terms-info-grid">
                    <h3>VI. Cơ chế giải quyết khiếu nại, tranh chấp trên mạng xã hội FUNNY VIDEO</h3>
                    <ol>
                        <li><p class="terms-info-text">Tranh chấp giữa các thành viên sử dụng mạng xã hội FUNNY VIDEO với chúng tôi.
                            </p>
                            <ol>
                                <li><p class="terms-info-text">Mọi khiếu nại, khiếu kiện nếu có thì sẽ được chúng tôi giải quyết nhanh chóng. Khi có khiếu nại, vui lòng thông báo cho chúng tôi qua email, điện thoại, hoặc đến trực tiếp địa chỉ mà chúng tôi niêm yết trên trang chủ mạng xã hội FUNNY VIDEO. Chúng tôi sẽ xem xét và phản hồi sớm nhất nhưng không quá 07 ngày kể từ ngày tiếp nhận thông tin khiếu nại. Chúng tôi có bộ phận giải quyết khiếu nại tiếp nhận và sẽ phản hồi cho các bạn qua email mà bạn đã đăng ký.</p></li>
                                <li><p class="terms-info-text">Nếu bạn khiếu nại, khiếu kiện chúng tôi đến các cơ quan chức năng thì chúng tôi sẽ phải tuân thủ theo các trình tự thủ tục mà pháp luật quy định. Việc khiếu nại đến cơ quan chức năng sẽ phức tạp, chúng tôi khuyến khích các hình thức giải quyết thông qua biện pháp thương lượng.</p></li>
                            </ol>
                        </li>
                        <li><p class="terms-info-text">Tranh chấp giữa cá nhân với cá nhân là thành viên của FUNNY VIDEO; Giữa cá nhân là thành viên FUNNY VIDEO với cá nhân, tổ chức không phải là thành viên FUNNY VIDEO.
                            </p>
                            <ol>
                                <li><p class="terms-info-text">Chúng tôi chịu trách nhiệm về các nội dung như quy định tại điểm B, Mục III Thỏa thuận này. Chúng tôi không thể chịu trách nhiệm về tính chính xác các thông tin mà các thành viên truyền đưa trên mạng xã hội. Do đó khi phát sinh khiếu nại, trước tiên chúng tôi có thể ẩn nội dung khiếu nại, đồng thời hãy gửi cho chúng tôi biết nội dung khiếu nại chi tiết và chứng cứ đính kèm qua email hoặc trực tiếp. Chúng tôi sẽ kiểm tra, yêu cầu các bên chứng minh. Nếu bên nào không chứng minh được thì chúng tôi sẽ gỡ bỏ nội dung của người vi phạm.</p></li>
                                <li><p class="terms-info-text">Việc khiếu nại, khiếu kiện giữa các cá nhân, tổ chức thông qua các cơ quan pháp luật thì chúng tôi chỉ đóng vai trò là người có quyền và nghĩa vụ liên quan và chúng tôi sẽ tham dự theo các quy định của pháp luật.</p></li>
                            </ol>
                        </li>
                        
                    </ol>
                </div>
                <div class="terms-info-grid">
                    <h3>VII. Chính sách thu thập và xử lý dữ liệu cá nhân người sử dụng.</h3>
                    <p></p>
                     <ol>
                        <li><p class="terms-info-text">Chúng tôi nhận được một số thông tin khác nhau về bạn, bao gồm:</p></li>
                        <li><p class="terms-info-text">Thông tin của bạn</p></li>
                        <li><p class="terms-info-text">Thông tin của bạn là thông tin bắt buộc phải nhập khi bạn đăng ký tài khoản trên trang web, wap và thông tin bạn chọn để chia sẻ.</p></li>
                        <li><p class="terms-info-text">Thông tin đăng ký</p>
                            <ol>
                                <li><p class="terms-info-text">Khi bạn đăng ký tài khoản FUNNY VIDEO, bạn được yêu cầu cung cấp thông tin như tên, địa chỉ email, ngày sinh và giới tính, chứng minh thư. Trong một số trường hợp, bạn có thể đăng ký bằng thông tin khác, như số điện thoại của bạn.</p></li>
                            </ol>
                        </li>
                        <li><p class="terms-info-text">Thông tin bạn chọn để chia sẻ</p>
                            <ol>
                                <li><p class="terms-info-text">Thông tin của bạn cũng bao gồm thông tin bạn chọn để chia sẻ trên FUNNY VIDEO, như khi bạn đăng cập nhật trạng thái, tải lên ảnh hoặc bình luận về tin của bạn bè.</p></li>
                            </ol>
                        </li>
                        <li><p class="terms-info-text">Thông tin mà người khác chia sẻ về bạn</p>
                            <ol>
                                <li><p class="terms-info-text">Chúng tôi nhận được thông tin về bạn từ bạn bè và những người khác, như khi họ tải lên thông tin liên hệ của bạn, đăng ảnh của bạn, đánh dấu bạn vào ảnh hoặc cập nhật trạng thái hoặc tại một vị trí hoặc thêm bạn vào một nhóm.</p></li>
                                <li><p class="terms-info-text">Thông tin khác mà chúng tôi nhận được về bạn</p></li>
                                <li><p class="terms-info-text">Chúng tôi cũng nhận được những loại thông tin khác về bạn:Khi bạn đăng những nội dung như ảnh hoặc video trên FUNNY VIDEO, chúng tôi có thể nhận thêm dữ liệu liên quan như thời gian, ngày và địa điểm bạn chụp ảnh hoặc quay video</p></li>
                                <li><p class="terms-info-text">Cách chúng tôi sử dụng thông tin nhận được</p></li>
                                <li><p class="terms-info-text">Chúng tôi sử dụng thông tin nhận được về bạn liên quan đến các dịch vụ và tính năng mà chúng/ tôi cung cấp.</p></li>
                            </ol>
                        </li>
                        
                        <li><p class="terms-info-text"> Để lưu trữ thông tin cá nhân về bạn tối thiểu 2 năm đối với các thông tin về tài khoản, thời gian đăng nhập, đăng xuất, địa chỉ IP của người sử dụng và nhật ký xử lý thông tin được đăng tải</p><p></p></li>
                        <li><p class="terms-info-text">Để hiển thị theo yêu cầu của bạn.</p><p></p></li>
                        <li><p class="terms-info-text">Để thực hiện gợi ý cho bạn và thành viên khác của FUNNY VIDEO.</p><p></p></li>
                        <li><p class="terms-info-text">Ngoài các mục đích trên chúng tôi không được phép thu thập, sử dụng thông tin của bạn vào bất kỳ mục đích gì.</p><p></p></li>
                        <li><p class="terms-info-text">Để lưu trữ thông tin cá nhân về bạn tối thiểu 2 năm đối với các thông tin về tài khoản, thời gian đăng nhập, đăng xuất, địa chỉ IP của người sử dụng và nhật ký xử lý thông tin được đăng tải</p></li>
                        <li><p class="terms-info-text">Để hiển thị theo yêu cầu của bạn.</p></li>
                        <li><p class="terms-info-text">Để thực hiện gợi ý cho bạn và thành viên khác của FUNNY VIDEO.</p></li>
                        <li><p class="terms-info-text">Ngoài các mục đích trên chúng tôi không được phép thu thập, sử dụng thông tin của bạn vào bất kỳ mục đích gì.</p></li>
                    </ol>
                </div>
                <div class="terms-info-grid">
                    <h3>VIII. Chính sách bảo vệ thông tin cá nhân, thông tin riêng của người sử dụng dịch vụ mạng xã hội.</h3>
                    <p></p>
                    <ol>
                        <li><p class="terms-info-text">Chúng tôi cũng xây dựng bộ lọc cảnh báo thành viên khi đăng thông tin có nội dung vi phạm, mọi hình thức vi phạm sẽ bị xử lý theo quy định.</p></li>
                        <li><p class="terms-info-text">Chúng tôi đảm bảo các thông tin cá nhân, thông tin riêng sẽ được bảo mật một cách tuyệt đối theo yêu cầu của bạn. Chúng tôi chỉ cung cấp các thông tin cá nhân, thông tin của bạn theo yêu cầu của cơ quan pháp luật có thẩm quyền.</p></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->display('layouts/footer.phtml'); ?>


