<div class="footer">
    <div class="container">
        <div class="col-md-3 footer-left-w3">
            <h4>Contact</h4>
            <ul>
                <li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></li>
                <li><a href="mailto:example@mail.com"><h6>ex@mail.com</h6></a></li>
            </ul>
            <ul>
                <li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></li>
                <li><h6>+18045678834</h6></li>
            </ul>
            <ul>
                <li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></li>
                <li><h6>4th Avenue,London</h6></li>
            </ul>
            <ul>
                <li><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span></li>
                <li><h6>(0033)6544 5453 644</h6></li>
            </ul>
        </div>
        <div class="col-md-5 footer-middle-w3">
            <h4>Latest Games</h4>
            
            <div class="col-md-3 img-w3-agile">
                <a href="single.html"><img src="/template/images/ng1.jpg" alt=" " /></a>
            </div>
            
            <div class="clearfix"></div>
        </div>
        <div class="col-md-4 footer-right-w3">
            <a href="index.html"><h4>Games <img src="/template/images/f1.png" alt=" " /> Zone</h4></a>
            <p>Donec lobortis diam eu auctor porta. Phasellus in elementum tortor, sit amet imperdiet urna pellentesque non risus porta.</p>
            <p class="agileinfo">Suspendisse convallis malesuada libero, non rutrum arcu pellentesque lacinia.</p>
        </div>
        <div class="clearfix"></div>
        <div class="copyright">
            <p>&copy; 2017 Games Zone. All Rights Reserved | Design by <a href="http://w3layouts.com/" target="_blank"> W3layouts </a></p>
        </div>
    </div>
</div>