<!--A Design by W3layouts 
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?php echo $site['title'];?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="keywords" content="<?php echo $site['keywords'];?>" />
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <!-- css -->
        <link href="/template/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
        <link rel="stylesheet" href="/template/css/flexslider.css" type="text/css" media="screen" property="" />
        <link href="/template/css/style.css" rel="stylesheet" type="text/css" media="all" />	
        <!--// css -->
        <!-- font -->

        <script src="/template/js/jquery.min.js"></script>
        <script src="/template/js/bootstrap.js"></script>

    </head>
    <body> 