<nav class="navbar navbar-default">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a  href="<?php echo $site['siteurl'];?>gameq/index"><h1><?php echo $site['title'];?> <img src="/template/images/c1.png" alt=" " /> Zone</h1></a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <?php if($menus){foreach ($menus as $key => $value){ ?>
                <li class="hover-effect"><a href="<?php echo $value['url'];?>"><?php echo $value['name'];?></a></li>
                <?php }}?>
            </ul>
        </div>
    </div>
</nav>