<div class="container">
    <div class="row">
        <style>
            .classAlert{
                border: 2px solid #E91E63;
                color: #E91E63;background-color: #ffffff;
                border-radius: 0px;
                margin-top: 5px;
            }
            .classUser{    
                padding: .7em 1em;
                background: #E91E63;
                color: #fff;
                margin-right: 2em;
                border-radius: 60%;
                font-style: normal;
            }
            b.msisdn{
                color:#e91e63;
            }
            button.signin{
                float: right;
                padding: 7px 15px;
                background-color: transparent;
                border: 2px solid rgb(2, 24, 136);
                outline: transparent;
                color: rgb(2, 24, 136);
                border-radius: 0px;
            }
            button.signin:hover {
                color: #FFf;
                border: 2px solid #FF166D;
                background: #FF166D;
            }
        </style>
        <div class="col-md-12">
            <div class="alert alert-danger classAlert" role="alert">
                <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>
                <span class="sr-only"></span>
                không nhận diện được thuê bao. Vui lòng truy cập bằng 3G/4G của Viettel hoặc đăng nhập để sử dụng DV
            </div>
            <?php if ($login) { ?>  <!--登录MT-->
                <i><span class="glyphicon glyphicon-user classUser" aria-hidden="true"></span></i>
                <span><b class="msisdn"> Hi: [<?php echo getmsisdn(); ?>]</b></span>
            <?php } ?>
        </div>
        <?php if (!$login) { ?>  <!--未登录MT-->
            <?php
            if (netType() == '3G') {
                $count = count(videoURL());
                $md = 12 / $count;
                foreach (videoURL() as $val) {
                    ?>
                    <div class="col-xs-12 col-sm-6 col-md-<?php echo $md; ?> service-grid-agileits">
                        <a href="<?php echo $val[0]; ?>"><?php echo $val[1]; ?></a>
                    </div>
            <?php }} else { ?>  <!--WIFI-->
                    <div class="col-md-12">
                        <button class="btn btn-default signin" type="button" data-toggle="modal" data-target="#signModal">Sign in</button>
                    </div>
            <?php } ?>
        <?php } ?>
    </div>
</div>

<!--登录模态框-->
 <style>
     .modal{
        margin-top: 12%;
     }
    .signin-form input.text{
        width: 100%;
    }
    .signin-title,.signin-form  label{
        color: #E91E63;
        font-weight: 700;
    }
    .radiusLeftClass{
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }
    .radiusRightClass{
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }
    .telcoGroup{
        margin-bottom: 10px;
    }
    .telcoGroup button.btn{
        border: 1px solid rgb(2, 24, 136);
    }
    .telcoGroup button.btn:hover{
        color: #FFf;
        border: 1px solid #FF166D;
        background: #FF166D;
    }
    .selectClass{
        color: #FFf;
        border: 1px solid #FF166D;
        background: #FF166D;
    }
</style>
<div class="modal fade" id="signModal" tabindex="-1" role="dialog" aria-labelledby="signModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h5 class="modal-title signin-title" id="myModalLabel">Sign in</h5>
            </div>
            <div class="modal-body">
                <div class="contact-agileinfo">
                    <?php 
                        $Telco_array = getTelco();
                        $operator = $Telco_array['operator'];
                    ?>
                    <div class="col-md-6 contact-left-agile">
                        <div class="address-w3-agileits" id="address">
                            <h4>Đăng Nhập </h4>
                            <address>
                                <ul>
                                    <li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> "số điện thoại/mật khẩu" để đăng nhập. Nếu Quý khách quên mật khẩu, soạn MK BM gửi 9029.</li>
                                    <li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>-Nếu Quý khách chưa đăng ký dịch vụ hãy soạn: DK BM gửi 9029 (3.000đ/ngày, gia hạn hàng ngày). </li>
                                    <li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>- DV sử dụng được trên các dòng máy dùng hệ điều hành Android hoặc Java.</li>
                                </ul>
                            </address>
                        </div>
                    </div>
                   
                    <div class="col-md-6 contact-right-w3">
                        <form  class="signin-form" onsubmit="return false;">
                            <div class="btn-group telcoGroup" role="group" >
                                <button type="button" class="btn btn-default telcoClass radiusLeftClass <?php echo $operator=='viettel'? 'selectClass':''; ?>" value="viettel">viettel</button>
                                <button type="button" class="btn btn-default telcoClass <?php echo $operator=='vinaphone'? 'selectClass':''; ?>" value="vinaphone">vinaphone</button>
                                <button type="button" class="btn btn-default telcoClass radiusRightClass <?php echo $operator=='mobifone'? 'selectClass':''; ?>" value="mobifone">mobifone</button>
                            </div>
                            <div class="form-group">
                                <label for="InputName">Số điện thoại:</label>
                                <input type="text" class="text" id="msisdn" name="msisdn"  required="">
                            </div>
                            <div class="form-group">
                                <label for="InputPass">Mật Khẩu :</label>
                                <input type="password" class="text" id="password" name="password" required="">
                            </div>
                            <input type="button" id="submitButton" class="more_btn" value="Login">
                        </form>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/dialog/jq_mydialog.js"></script>
<link href="/dialog/my_dialog.css" type="text/css" rel="stylesheet" />
<script>
    $(document).ready(function () {
        $(document).on('click', '.telcoGroup .telcoClass', function () {
            $(this).siblings('.telcoClass').removeClass('selectClass');//  移除同类状态标示
            $(this).addClass('selectClass');
            $('#submitButton').attr('data', $(this).val());// 设置值
        });

        // 保存状态
        $('#submitButton').click(function () {
            //console.log(11111);
            var msisdn = $('#msisdn').val();
            var password = $('#password').val();
            var telco = $(this).attr('data');
            if(typeof(telco)=="undefined" || telco.length < 1){
                $('.telcoGroup').after('<p class="text-danger">Please select mobile operators</p>');
                setTimeout(function(){
                    $('.telcoGroup').next().remove();
                }, 3000);
                return false;
            }
            $.post("/sub/mtlogin", {"msisdn": msisdn,"password":password,"telco":telco},
                function (data) {
                    if(data.status == 200){
                        var tip  = data.content;
                        $.myalert({
                            width: "50%",
                            content: '<b>'+tip+'</b>',
                            confirm_btn_click: function (e) { //确认按钮点击事件
                                $.myalert("getDialog").mydialog("hide");                                                           
                                //跳转首页
                                window.location.href='/';
                            }
                        });
                        // 关闭弹窗
                        $('#small-dialog').find('.mfp-close').trigger('click');
                    }else if(data.status == 401){
                        $('#password').after('<p class="text-danger">'+data.content+'</p>');
                        setTimeout(function(){
                            $('#password').next().remove();
                        }, 3000);
                        return false;
                    }
                    console.log(data); //  2pm
                }, "json");
        });
    });
</script>
