<?php $this->display('layouts/header.phtml'); ?>
<?php $this->display('layouts/navbar.phtml'); ?>
<?php $this->display('layouts/sidebar.phtml'); ?>
<!--视频播放器ckplayer  http://www.sucaihuo.com/jquery/16/1663/demo/-->
<script type="text/javascript" src="/ckplayer/ckplayer/ckplayer.js"></script>
<script type="text/javascript" src="/ckplayer/js/offlights.js"></script>
<style type="text/css">
    /* 一般浏览器不会出现下载按钮，只有谷歌浏览器会（低版本的右下角没有下载按钮，比如53.0版本) 。
    如果你的谷歌浏览器版本是54.0-57.0之间，并且也出现了视频右下角有按钮的情况都可以使用下面的代码。
    解决方法：*/
    video::-internal-media-controls-download-button {
        display:none;
    }
    video::-webkit-media-controls-enclosure {
        overflow:hidden;
    }
    video::-webkit-media-controls-panel {
        width: calc(100% + 30px); 
    }
    #a1{
        height:320px;
    }
</style>
<div class="show-top-grids">
    <div class="col-sm-8 single-left">
        <div class="song">
            <div class="song-info">
                <h3><?php echo $row['title']?></h3>	
            </div>
            <!---视频--->
            <div class="video-grid">
                <div id="a1"></div>
            </div>
        </div>
        <div class="song-grid-right">
            <div class="share">
                <h5>Share this</h5>
                <ul>
                    <li><a href="#" class="icon fb-icon">Facebook</a></li>
                    <li><a href="#" class="icon dribbble-icon">Dribbble</a></li>
                    <li><a href="#" class="icon twitter-icon">Twitter</a></li>
                    <li><a href="#" class="icon pinterest-icon">Pinterest</a></li>
                    <li><a href="#" class="icon whatsapp-icon">Whatsapp</a></li>
                    <li><a href="#" class="icon like">Like</a></li>
                    <li><a href="#" class="icon comment-icon">Comments</a></li>
                    <li class="view">200 Views</li>
                </ul>
            </div>
        </div>
        <div class="clearfix"> </div>
        <div class="published">
            <script>
                $(document).ready(function () {
                    size_li = $("#myList li").size();
                    x = 1;
                    $('#myList li:lt(' + x + ')').show();
                    $('#loadMore').click(function () {
                        x = (x + 1 <= size_li) ? x + 1 : size_li;
                        $('#myList li:lt(' + x + ')').show();
                    });
                    $('#showLess').click(function () {
                        x = (x - 1 < 0) ? 1 : x - 1;
                        $('#myList li').not(':lt(' + x + ')').hide();
                    });
                });
            </script>
            <div class="load_more">	
                <ul id="myList">
                    <li>
                        <h4>Published on <?php echo date('Y-m-d', strtotime($row['created_at']));?></h4>
                        <p> <?php echo $row['text']?></p>
                    </li>
                    <li>
                        <p>Nullam fringilla sagittis tortor ut rhoncus. Nam vel ultricies erat, vel sodales leo. Maecenas pellentesque, est suscipit laoreet tincidunt, ipsum tortor vestibulum leo, ac dignissim diam velit id tellus. Morbi luctus velit quis semper egestas. Nam condimentum sem eget ex iaculis bibendum. Nam tortor felis, commodo faucibus sollicitudin ac, luctus a turpis. Donec congue pretium nisl, sed fringilla tellus tempus in.</p>
                        <p>Nullam fringilla sagittis tortor ut rhoncus. Nam vel ultricies erat, vel sodales leo. Maecenas pellentesque, est suscipit laoreet tincidunt, ipsum tortor vestibulum leo, ac dignissim diam velit id tellus. Morbi luctus velit quis semper egestas. Nam condimentum sem eget ex iaculis bibendum. Nam tortor felis, commodo faucibus sollicitudin ac, luctus a turpis. Donec congue pretium nisl, sed fringilla tellus tempus in.</p>
                        <div class="load-grids">
                            <div class="load-grid">
                                <p>Category</p>
                            </div>
                            <div class="load-grid">
                                <a href="movies.html">Entertainment</a>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="all-comments">
            <div class="all-comments-info">
                <a href="#">All Comments (8,657)</a>
                <div class="box">
                    <form>
                        <input type="text" placeholder="Name" required=" ">			           					   
                        <input type="text" placeholder="Email" required=" ">
                        <input type="text" placeholder="Phone" required=" ">
                        <textarea placeholder="Message" required=" "></textarea>
                        <input type="submit" value="SEND">
                        <div class="clearfix"> </div>
                    </form>
                </div>
                <div class="all-comments-buttons">
                    <ul>
                        <li><a href="#" class="top">Top Comments</a></li>
                        <li><a href="#" class="top newest">Newest First</a></li>
                        <li><a href="#" class="top my-comment">My Comments</a></li>
                    </ul>
                </div>
            </div>
            <div class="media-grids">
                <div class="media">
                    <h5>Tom Brown</h5>
                    <div class="media-left">
                        <a href="#">

                        </a>
                    </div>
                    <div class="media-body">
                        <p>Maecenas ultricies rhoncus tincidunt maecenas imperdiet ipsum id ex pretium hendrerit maecenas imperdiet ipsum id ex pretium hendrerit</p>
                        <span>View all posts by :<a href="#"> Admin </a></span>
                    </div>
                </div>
                <div class="media">
                    <h5>Mark Johnson</h5>
                    <div class="media-left">
                        <a href="#">

                        </a>
                    </div>
                    <div class="media-body">
                        <p>Maecenas ultricies rhoncus tincidunt maecenas imperdiet ipsum id ex pretium hendrerit maecenas imperdiet ipsum id ex pretium hendrerit</p>
                        <span>View all posts by :<a href="#"> Admin </a></span>
                    </div>
                </div>
                <div class="media">
                    <h5>Steven Smith</h5>
                    <div class="media-left">
                        <a href="#">

                        </a>
                    </div>
                    <div class="media-body">
                        <p>Maecenas ultricies rhoncus tincidunt maecenas imperdiet ipsum id ex pretium hendrerit maecenas imperdiet ipsum id ex pretium hendrerit</p>
                        <span>View all posts by :<a href="#"> Admin </a></span>
                    </div>
                </div>
                <div class="media">
                    <h5>Marry Johne</h5>
                    <div class="media-left">
                        <a href="#">

                        </a>
                    </div>
                    <div class="media-body">
                        <p>Maecenas ultricies rhoncus tincidunt maecenas imperdiet ipsum id ex pretium hendrerit maecenas imperdiet ipsum id ex pretium hendrerit</p>
                        <span>View all posts by :<a href="#"> Admin </a></span>
                    </div>
                </div>
                <div class="media">
                    <h5>Mark Johnson</h5>
                    <div class="media-left">
                        <a href="#">

                        </a>
                    </div>
                    <div class="media-body">
                        <p>Maecenas ultricies rhoncus tincidunt maecenas imperdiet ipsum id ex pretium hendrerit maecenas imperdiet ipsum id ex pretium hendrerit</p>
                        <span>View all posts by :<a href="#"> Admin </a></span>
                    </div>
                </div>
                <div class="media">
                    <h5>Mark Johnson</h5>
                    <div class="media-left">
                        <a href="#">

                        </a>
                    </div>
                    <div class="media-body">
                        <p>Maecenas ultricies rhoncus tincidunt maecenas imperdiet ipsum id ex pretium hendrerit maecenas imperdiet ipsum id ex pretium hendrerit</p>
                        <span>View all posts by :<a href="#"> Admin </a></span>
                    </div>
                </div>
                <div class="media">
                    <h5>Peter Johnson</h5>
                    <div class="media-left">
                        <a href="#">

                        </a>
                    </div>
                    <div class="media-body">
                        <p>Maecenas ultricies rhoncus tincidunt maecenas imperdiet ipsum id ex pretium hendrerit maecenas imperdiet ipsum id ex pretium hendrerit</p>
                        <span>View all posts by :<a href="#"> Admin </a></span>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-4 single-right">
        <h3>Up Next</h3>
        <div class="single-grid-right">
            <?php if ($contents) {
                foreach ($contents as $key => $vv) { ?>
                    <div class="single-right-grids">
                        <div class="col-md-4 single-right-grid-left">
                            <a href="/index/show?id=<?php echo $vv['id']; ?>"><img src="<?php echo $vv['thumb']; ?>" alt="" /></a>
                        </div>
                        <div class="col-md-8 single-right-grid-right">
                            <a href="/index/show?id=<?php echo $vv['id']; ?>" class="title"> <?php echo $vv['title']; ?></a>
                            <p class="author"><a href="#" class="author"><?php echo $vv['authorid']; ?></a></p>
                            <p class="views"><?php echo $vv['click']; ?> views</p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
    <?php }
} ?>
        </div>
    </div>
    <div class="clearfix"> </div>
</div>
<?php $this->display('layouts/footer.phtml'); ?>
<script type="text/javascript">
    //如果你不需要某项设置，可以直接删除，注意var flashvars的最后一个值后面不能有逗号
    function loadedHandler() {
        if (CKobject.getObjectById('ckplayer_a1').getType()) {//说明使用html5播放器
            console.log('播放器已加载，调用的是HTML5播放模块');
            CKobject.getObjectById('ckplayer_a1').addListener('time', timeHandler);  // 监听播放时间
        } else {
            console.log('播放器已加载，调用的是Flash播放模块');
            console.getObjectById('ckplayer_a1').addListener('time', 'timeHandler'); // 监听播放时间
        }
    }

    //执行监听时间回调方法
    var isNumber = true;//定义只判断一次
    function timeHandler(t) {
        if (t > 10 && isNumber) {

            CKobject.getObjectById('ckplayer_a1').videoPause();//暂停播放
            CKobject.getObjectById('ckplayer_a1').removeListener('time', 'timeHandler');
            isNumber = false;
            console.log('这里的弹出提示代码可以改成执行其它动作的代码');
            //这时是判断当播放时间大于10，并且没有执行过试看判断的情况下进行判断。
            //这里可以弹出登陆层或弹幕提示层


        }
    }


    var vf = GetQueryString('id');
    var flashvars = {
        //f:'http://movie.ks.js.cn/flv/other/1_0.mp4',  
        f: '/index/show?vfs=' + vf,
        a: vf,
        s: 1,
        c: '0', // 1 读取配置ckplayer.xml
        e: '1',
        p: '0', //视频默认0是暂停，1是播放，2是不加载视频
        i: 'http://www.ckplayer.com/static/images/cqdw.jpg',
        wh: '16:9',
        h: 1,
        loaded: 'loadedHandler'//当播放器加载完成后发送该js函数loadedHandler
    };
    var params = {bgcolor: '#FFF', allowFullScreen: true, allowScriptAccess: 'always', wmode: 'transparent'};
    var video = ['/index/show?id=' + vf + '->ajax/post/utf-8'];
    CKobject.embed('/ckplayer/ckplayer/ckplayer.swf', 'a1', 'ckplayer_a1', '100%', '100%', true, flashvars, video, params);  // true 优先使用H5 

</script>
