<!DOCTYPE html>
<html lang="en">
    <head>
         <title><?php echo $site['title'];?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="keywords" content="<?php echo $site['keywords'];?>" />
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <!-- bootstrap -->
        <link href="/assets/css/bootstrap.min.css" rel='stylesheet' type='text/css' media="all" />

        <!-- Custom styles for this template -->
        <link href="/assets/css/style-login.css" rel="stylesheet">
        <link href="/assets/css/style-responsive.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->

        <div id="login-page">
            <div class="container">
                <form class="form-login" action="/sub/login" method="post">
                    <h2 class="form-login-heading">sign in now</h2>
                    <div class="login-wrap">
                        <input type="text" name="username" class="form-control" placeholder="User Email">
                        <br>
                        <input type="password" name="password" class="form-control" placeholder="Password">
                        <label class="checkbox">
                            <span class="pull-right">
                                
                            </span>
                        </label>
                        <button class="btn btn-theme btn-block" type="submit"><i class="fa fa-lock"></i> SIGN IN</button>
                        <hr>
                        <div class="login-social-link centered">
                            <div class="registration">
                                <a class="" href="/">
                                    Back Homepage
                                </a>
                            </div>
                        </div>
                </form>
            </div>
        </div>

        <!-- js placed at the end of the document so the pages load faster -->
        <script src="/assets/js/jquery-1.11.1.min.js"></script>
       
        <!--BACKSTRETCH-->
        <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
        <script type="text/javascript" src="/assets/js/jquery.backstretch.min.js"></script>
        <script>
            $.backstretch("/assets/images/login-bg.jpg", {speed: 500});
        </script>

    </body>
</html>
