<?php $this->display('layouts/header.phtml'); ?>
<?php $this->display('layouts/navbar.phtml'); ?>
<?php $this->display('layouts/sidebar.phtml'); ?>

<div class="show-top-grids">
    <div class="col-sm-10 show-grid-left main-grids">
        <?php if($contents){ foreach($contents as $key => $value){ ?>
            <div class="recommended">
            <div class="recommended-grids">
                <div class="recommended-info">
                    <?php if($key == 0){?>
                        <div class="heading"><h3>Marathi</h3></div>
                        <div class="heading-right"><a  href="#small-dialog8" class="play-icon popup-with-zoom-anim">Subscribe</a></div>
                        <div class="clearfix"> </div>
                    <?php }?>
                </div>
                <?php  foreach ($value as $kk => $vv){?>
                    <div class="col-md-2 resent-grid recommended-grid show-video-grid">
                        <div class="resent-grid-img recommended-grid-img">
                            <a href="/index/show?id=<?php echo $vv['id'];?>"><img src="<?php echo $vv['thumb'];?>" alt="" /></a>
                            <div class="time small-time show-time">
                                <p><?php echo $vv['time_length'];?></p>
                            </div>
                            <div class="clck show-clock">
                                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="resent-grid-info recommended-grid-info">
                            <h5><a href="/index/show?id=<?php echo $vv['id'];?>" class="title"><?php echo $vv['title'];?></a></h5>
                            <p class="author"><a href="#" class="author"><?php echo $vv['authorid'];?></a></p>
                            <p class="views"><?php echo $vv['click'];?> views</p>
                        </div>
                    </div>
                <?php }?>               
              <div class="clearfix"> </div>
            </div>
            </div>           
        <?php }}?>
       
        <center>
           <?php echo $page;?>
        </center>
    </div>
    <!--排序TOP -->
    <div class="col-md-2 show-grid-right">
        <h3>Upcoming Channels</h3>
        <?php if($category_top){ foreach ($category_top as $kk => $val){?>
        <div class="show-right-grids">
            <ul>
                <li class="tv-img"><a href="#"><img src="/assets/images/tv.png" alt="" /></a></li>
                <li><a href="/index/show?id=<?php echo $val['id']?>"><?php echo subtext($val['title'],16);?></a></li>
            </ul>
        </div>
        <?php }}?>
    </div>
    <div class="clearfix"> </div>
</div>

<?php $this->display('layouts/footer.phtml'); ?>